### ISSUE TITLE
Update to README.md for Umbrel Node Instructions

### ISSUE THREAD

**Issue by stoic-unicorn** [alexbosworth/balanceofsatoshis#101]
First off, these tools are amazing, thank you!!

In the section about running bos via docker and passing in the hostname variable to automatically detect your node for Umbrel, it might be good to add a note that IP address could be different (for nubes like me where this isn't immediately obvious)

Also, might be helpful to just note that Umbrel nodes do come with docker installed (again, for nubes like me) as at first I didn't realize this and was looking for other ways to install.

**Comment by alexbosworth** [comment]
I don't have an Umbrel node setup so if someone wants to write a guide that would be cool, I've tried to make it auto detect Umbrel and I've added some notes on umbrel in the readme though

If someone does want to write a guide, it could also be a good yalls.org article

**Comment by ghtsto** [comment]
Just a heads up to anyone that might stumble upon this issue, if you run the command on your Umbrel node, you should change the IP to the local Umbrel IP (ie. 127.0.0.1).

Example:
`docker run -it --rm --network="host" --add-host=umbrel.local:127.0.0.1 -v $HOME/.bos:/home/node/.bos -v $HOME/umbrel/lnd:/home/node/.lnd:ro alexbosworth/balanceofsatoshis -v`

**Comment by alexbosworth** [comment]
I'm not sure if the local ip is always 127.0.0.1 - I have an Umbrel example here where it is a different ip: https://github.com/alexbosworth/balanceofsatoshis#docker-load

**Comment by ghtsto** [comment]
I'm using "umbrel-os" (their Raspberry Pi distro) and it works with the localhost IP and the LND IP as automatically set in the .env (for me, it's in the 10.x space). In any case, I think the README could have a small update which states the IP to use should be your local LND IP.

**Comment by alexbosworth** [comment]
Go for it if you want to edit the README:  https://github.com/alexbosworth/balanceofsatoshis/edit/master/README.md

**Comment by stoic-unicorn** [comment]
looks like ghtsto made all the updates I had been thinking of, thank you! I think this can be closed.
