### ISSUE TITLE
Documentation error with umbrel usage

### ISSUE THREAD

**Issue by steff123** [alexbosworth/balanceofsatoshis#104]
Hey,
when using umbrel with docker you have provide the .bos directory to the container.

The option
-v $HOME/.bos:/home/node/.bos

is missing in the README.

**Comment by alexbosworth** [comment]
maybe you can take a look at the readme, if it is wrong you can press the edit button and propose a change for umbrel

**Comment by steff123** [comment]
All fine :+1:
