### ISSUE TITLE
Lost sats on rebalance

### ISSUE THREAD

**Issue by grunch** [alexbosworth/balanceofsatoshis#107]
I've been playing with rebalance which I found very useful but today something weird happened.

```
$ bos rebalance --in 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f \
> --out 031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0 \
> --max-fee 200 \
> --amount=1000000

outgoing_peer_to_increase_inbound: Breez 031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0
incoming_peer_to_decrease_inbound: BCash_Is_Trash 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f
rebalance_target_amount:           0.01000000

circular_rebalance_for: grunch.dev 024b8019795ec753fcdb1eb21ecd319bfab6a8b05e017f357dc5f052a181fb8c91

evaluating: 
  - 599112x1453x1 ★ ★ ★ ★
  - Breez 031015a7839468a3c266d662d5bb21ea4cea24226936e2864a7ca4f2c3939836e0. Fee rate: 0.00% (4)
  - 584571x2641x0
  - BCash_Is_Trash 0298f6074a454a1f5345cb2a7c6f9fce206cd0bf675d177cdbf0ca7508dd28852f. Fee rate: 0.00% (36)
  - 685981x1182x1

evaluating_amount: 499602
evaluating_amount: 749403
evaluating_amount: 874303
evaluating_amount: 936753
evaluating_amount: 905528

rebalance: 
  - 
    increased_inbound_on: Breez
    liquidity_inbound:    0.00958641
    liquidity_outbound:   0.01032762
  - 
    decreased_inbound_on: BCash_Is_Trash
    liquidity_inbound:    0.08125369
    liquidity_outbound:   0.00874304
  - 
    rebalanced:           0.00874317
    rebalance_fees_spent: 0.00000013
    rebalance_fee_rate:   0.00% (15)

```
I got **958,641** out of my channel with breez, but I only got **874,317** to my channel with bcash_is_trash, with a fee of 13 (or 15?) satoshis, I set the `max-fee` parameter to 200, but it looks like somehow I lost **84,337** satoshis, this was a perfect circular rebalance with only the two hops I wanted to be involved, how this can happened?

**Comment by alexbosworth** [comment]
I'd look for pending HTLCs, while it is evaluating a rebalance it will try various HTLCs that can never resolve as spent because they use a random preimage but LND won't know that's the case and so it will deduct them from your balance while they are pending

**Comment by alexbosworth** [comment]
You can also use the accounting commands to see what payments were sent

**Comment by grunch** [comment]
I did a lncli listpayments and I see the payment was for 874,317 sats, the final amount I see reflected on the destination channel.

But why I got this output `liquidity_inbound:    0.00958641`? is this because the pending htlcs?

**Comment by alexbosworth** [comment]
It just shows the remote balance at the moment so also potentially something else happened on the channel while you were rebalancing

**Comment by grunch** [comment]
something else like what? I don't have recent forwarding payments, it's just weird

**Comment by grunch** [comment]
I wanted to create a bash script to rebalance some channels with bos, do you think it's risky?

**Comment by alexbosworth** [comment]
if you run the accounting commands it will show you the records it knows about and you can look for what might have shifted the balance

**Comment by alexbosworth** [comment]
a script to rebalance is potentially risky depending on the conditions you put on the script, the major risk is that you are running the script uneconomically, like if you have two rebalance operations that work against each other and every time they run you lose some money to routing fees

There is a safety feature `--out-channel` you can set to specify channels, that can be useful in a bash script to lock it down a bit

You might also use the `--minutes` argument or use unix timeout in order to avoid the rebalance from running too long

**Comment by grunch** [comment]
Ok, thanks for the advice on the rebalance script, I'll take a look on accounting, I'll close this issue.

**Comment by alexbosworth** [comment]
You can also look at the native records with lncli, in theory if there is a balance change there is always a corresponding transaction that changed it
