### ISSUE TITLE
Output to CSV addresses and amounts when running open command

### ISSUE THREAD

**Issue by keblek** [alexbosworth/balanceofsatoshis#110]
Currently, I have to copy and paste each address and amount to my software wallet to construct my Tx.

This step is tedious and error prone.

It would be so useful to me if instead `bos` would also write to a csv file the addresses and the amount instead of just writing them to standard out.

My wallet could then easily open the file and use it to construct a Tx, double check that everything looks good and sign.

The CSV file could look like this;

Address, Amount (sats), Alias
bc1n...n55e, 1000000, OpenNode
bc1n...n65e, 10000000, Wallet of Satoshi
bc1n...n55a, 5000000, Bcash sucks

**Comment by alexbosworth** [comment]
What is the wallet software type?

**Comment by keblek** [comment]
I am using sparrow wallet. Honestly, any format would be fine as I can easily write a small script that can convert between most file formats.

**Comment by alexbosworth** [comment]
How about copy and paste, does it have any way to paste in multiple outputs? The current output is designed to be pasted into electrum's pay to many

**Comment by keblek** [comment]
That's what I was doing before hand but I would have to do each entry one by one with separate copy paste for each address and amount. 

I will close this, the easy way out of this is for sparrow to copy electrum.

**Comment by alexbosworth** [comment]
Yeah if sparrow can add a way to paste a list I can look into formatting to support that, or standardizing on electrum style would also be nice
