### ISSUE TITLE
bos rebalance --max-fee 1500 - Result: RebalanceFeeRateTooHigh   -     needed_max_fee_rate: 1179

### ISSUE THREAD

**Issue by agd-media** [alexbosworth/balanceofsatoshis#112]
When I try to rebalance with a max fee of 1500 bos says error: I would need 1179. Makes no sense.

**Comment by alexbosworth** [comment]
If it says max fee rate then you need to specify max fee rate not max fee

**Comment by agd-media** [comment]
Thanks for clearing that up!
