### ISSUE TITLE
Indicate the Node Alias of the other end of the channel in bos rebalance

### ISSUE THREAD

**Issue by BhaagBoseDK** [alexbosworth/balanceofsatoshis#116]
in bos rebalance sometimes you get a message 

`failure: TemporaryChannelFailure at 684557x2607x1 from sphinxrouting-6553d29959`

Now if I am not wrong, `684557x2607x1` is a channel at `sphinxrouting` which failed. 

```
 - sphinxrouting-6553d29959 028edb80cb2a4cfa10dc72fc0942ae42575e484480bf53c6373fc4d46240bfec62. Fee rate: 0.00% (3)
  - 684557x2607x1
  - My_Dude 02f1a08a1e33a9f670c464c3d66573ddd5d05b4231bb81b0b96c58eff7b730e332. Fee rate: 0.00% (0)
  - 686711x1372x0
  - Boltz 026165850492521f4ac8abd9bd8088123446d126f648ca35e60f88177dc149ceb2. Fee rate: 0.00% (3)
  - 686867x186x0
  - ⚡️ ✋ rockshouse 031c7ecff228dfe6054307ee49c8616998af5f8d4436f13c07d211aeb6c0ec87f7. Fee rate: 0.00% (6)
  - 691762x2154x0

```
Indeed this is a channel with My_Dude as you can see in the message few lines above this failure line.

Would it be possible to put the alias of the other end of channel peer in this message 

Something on the line of

`failure: TemporaryChannelFailure at 684557x2607x1 from sphinxrouting-6553d29959 -> My_Dude`

## Reasons to Not Implement

- Another alias lookup will require more time
- Listing multiple aliases de-emphasizes the source of the failure

**Comment by alexbosworth** [comment]
How would repeating it help with your usage flow

**Comment by BhaagBoseDK** [comment]
1- aliases are easily recognised compared to channel id

2- the output is passed to grep to look for temporary failure and from there a list of consistently failing channel can be prepared for adding to avoid list.
