### ISSUE TITLE
Error on use REBALANCE bos in Raspiblitz

### ISSUE THREAD

**Issue by GabrielRCL** [alexbosworth/balanceofsatoshis#117]
I can't do the rebalance even accepting any type of max fee, no matter what max fee I put.

print error:
http://i.prntscr.com/d2wVi5DxRAeXnLjkGDfZFA.png

error:
evaluating_amount: 321028

evaluating_amount: 481542

evaluating_amount: 401285

evaluating_amount: 441413

err:
  - 400
  - RebalanceFeeRateTooHigh
  -
    needed_max_fee_rate: 506

**Comment by alexbosworth** [comment]
you must specify `--max-fee-rate`

**Comment by GabrielRCL** [comment]
Ah thank you!
and what is the difference between the max fee rate and the max fee?

**Comment by alexbosworth** [comment]
If you want to pay for a rebalance you have to opt in to a fee in both maximum absolute terms using `max-fee` and in % terms using `max-fee-rate`

The max fee is in sat, the max fee rate is in ppm

**Comment by GabrielRCL** [comment]
thx

**Comment by uskrusader** [comment]
**I'm having a similar issue, what am i missing?**

`$ bos rebalance --amount 350000 --max-fee-rate 5000 --in (channel) --out `(channel)`

......

```
valuating_amount: 172339

evaluating_amount: 258508

evaluating_amount: 301593

err: 
  - 400
  - RebalanceTotalFeeTooHigh
  - 
    needed_max_fee: 1659
    high_fee:       (channel)
```

**Comment by alexbosworth** [comment]
use the --max-fee option

**Comment by uskrusader** [comment]
**ahhh, I need to put both in the rebalance command!**  Reading helps

`$ bos rebalance --amount 350000 --max-fee 6000 --max-fee-rate 6000 --in channel --out channel`

Thanks Alex
