### ISSUE TITLE
Unclear what needs to be stored in logger.info

### ISSUE THREAD

**Issue by Quenos** [alexbosworth/balanceofsatoshis#120]
Having import all the necessary modules into my own code for "executeProbe" I'm getting a args.logger.info is not a function error.

Somewhere else in the code I found this:
      info: {
        outgoing_peer_to_increase_inbound: nodeOut.alias,
        incoming_peer_to_decrease_inbound: nodeIn.alias,
        rebalance_target_amount: tokAsBigTok(tokens),
      },

But clearly this is not what executeProbe is expecting.

So what do  I need to put in logger?

**Comment by alexbosworth** [comment]
it expects a winston logger object: https://github.com/winstonjs/winston

like {info: line => console.log(line)} etc

**Comment by Quenos** [comment]
Really appreciate your fast response.
Thanks a bundle!
