### ISSUE TITLE
Telegram: add /testbot to send a test message to the bot

### ISSUE THREAD

**Issue by morrisonbrett** [alexbosworth/balanceofsatoshis#121]
`$ bos telegram --test-bot`

No flags. Keep it simple.

Sends a message to the bot confirming it's connected.

This would let users know if the node is properly connected to Telegram.

**Comment by alexbosworth** [comment]
When would this be used? If you run `bos telegram` and it connects, it should always immediately send a message to the bot saying that it was connected

**Comment by morrisonbrett** [comment]
I'm thinking if you have the telegram command setup to always be running, it would be helpful to invoke it without needing a /connect id and see that it is indeed connected.

**Comment by alexbosworth** [comment]
Telegram only allows one connection, but you could try /version or something in the bot itself to see if it's connected - it should still also say it connected when run in the daemon mode

**Comment by morrisonbrett** [comment]
Thanks. Agree it's not needed thanks to /version. Closing.
