### ISSUE TITLE
No response from the telegram bot

### ISSUE THREAD

**Issue by Dzjoeeles** [alexbosworth/balanceofsatoshis#127]
While installing BOS on ssh, i can not connect my telegram bot. 
I have to give in the connection code , but there is no response from the (personel) bot after the /connect command is given. 
I think something went wrong the first time i had to give in the connection code, and i have no idea how to 'reset' this..
Anybody with the same problem?

Grtz

**Comment by alexbosworth** [comment]
There is a help telegram channel you can join

**Comment by alexbosworth** [comment]
If you are using Umbrel there is a Telegram bot setup guide here: https://plebnet.wiki/wiki/Umbrel_-_Installing_BoS
