### ISSUE TITLE
bos rebalance --max-fee-rate seems to be ignored

### ISSUE THREAD

**Issue by agd-media** [alexbosworth/balanceofsatoshis#131]
Even though I put a maximum fee rate of 100, bos is still trying to use nodes with much higher fee rates. I would expect it to do what I set and keep trying until it finds a route with nodes that have a fee rate of <100. Instead I have to manually set the --avoid flag on nodes with a fee >100 and run the rebalance again and again, which is very time consuming.

**Comment by alexbosworth** [comment]
this is by design

**Comment by dannydeezy** [comment]
> , bos is still trying to use nodes with much higher fee rates. I would expect it to do what I set and keep trying until it finds a ro

may i ask why this is by design?

**Comment by alexbosworth** [comment]
the max fee rate is the rate to auto-accept, the fee rate tried shows you the fee rate to opt-in to

**Comment by dannydeezy** [comment]
> alexbosworth

and the idea is that the Lnd path-finding algo is presenting the lowest fee routes first?

**Comment by alexbosworth** [comment]
yeah that's correct

**Comment by dannydeezy** [comment]
> yeah that's correct

it seems the lnd routing algorithm may have been updated, as I don't think it is presenting the lowest fee option first. they're maybe doing some weighting by channel size too or something

example output of a `bos rebalance --out CoinGate` command with `lnd 0.14.2-beta`

(note a higher fee route is presented first)
```
outgoing_peer_to_increase_inbound: CoinGate 0242a4ae0c5bef18048fbecf995094b74bfb0f7391418d71ed394784373f41e4f3
incoming_peer_to_decrease_inbound: <REDACTED> <REDACTED>
rebalance_target_amount:           0.04294967

circular_rebalance_for: deezy 024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf

evaluating: 
  - 676038x1275x0 ★ ★ ☆ ☆
  - CoinGate 0242a4ae0c5bef18048fbecf995094b74bfb0f7391418d71ed394784373f41e4f3. Fee rate: 0.00% (3)
  - 724289x1527x1
  - coinhodler04108 0299797daa21faa6e4151517b286c41d4c7a8cb21fbfba59ca3bcd21a9f8392bd4. Fee rate: 0.04% (433)
  - 724069x1574x0
  - <REDACTED> <REDACTED> Fee rate: 0.00% (3)
  - <REDACTED>

failure: TemporaryChannelFailure at 724289x1527x1 from CoinGate

evaluating: 
  - 676038x1275x0 ★ ★ ☆ ☆
  - CoinGate 0242a4ae0c5bef18048fbecf995094b74bfb0f7391418d71ed394784373f41e4f3. Fee rate: 0.00% (3)
  - 638350x612x0
  - LNBIG.com [lnd-10] 02bb24da3d0fb0793f4918c7599f973cc402f0912ec3fb530470f1fc08bdd6ecb5. Fee rate: 0.02% (242)
  - 667410x56x0
  - <REDACTED> <REDACTED>. Fee rate: 0.00% (3)
  - <REDACTED>

failure: TemporaryChannelFailure at 638350x612x0 from CoinGate

```

**Comment by alexbosworth** [comment]
Yeah it is relative to the confidence which is factored into the cost

You can see the confidence as those stars at the top: `★ ★ ☆ ☆`

This behavior can be adjusted in lnd.conf routerrpc settings

**Comment by dannydeezy** [comment]
> 

sweet thanks i will check that out. i'm trying to find a good way to constantly monitor for possible cheap rebalance paths

**Comment by alexbosworth** [comment]
there's an option now to avoid max fee rate routes
