### ISSUE TITLE
Send doesn't work

### ISSUE THREAD

**Issue by rkfg** [alexbosworth/balanceofsatoshis#135]
And some other functions too (can't remember which ones exactly).
Running: `./bos send 03006fcf3312dae8d068ea297f58e2bd00ec1ffe214b793eda46966b6294a53ce6 --message "test" --dryrun`
Result:
```
err: 
  - 503
  - ExpectedCommitmentTypeInChannelMessage
```

`lnd` version is `0.13.99-beta commit=kvdb/v1.1.0-33-g3385d3841` (compiled myself, running on RPi 4/Raspbian/armv7, 32 bit), BoS is from `master`. This looks like a gRPC protocol change that's not handled correctly by the underlying library?

**Comment by alexbosworth** [comment]
I don't think that there is an issue yet I can link you, but this is a problem with lnd that it isn't returning results consistent with its past results

**Comment by rkfg** [comment]
Changed how? I mean reporting it as "Your program changed something so that other program no longer works" isn't very helpful. I don't think lnd developers would investigate and fix it. If you're not interested in fixing BoS so it works with lnd just say so and let's close this issue.

**Comment by rkfg** [comment]
I tried this in the latest version of BoS and lnd and it worked. Thanks for the fix!
