### ISSUE TITLE
Can't rebalance with any options

### ISSUE THREAD

**Issue by josephtyler** [alexbosworth/balanceofsatoshis#136]
I'm trying to rebalance with various options like this:

```
bos rebalance --amount=50000 --in=<node with inbound liquidity> --out=<node with outbound liquidity> --max-fee=1
bos rebalance --amount=50000 --in=<node with inbound liquidity>  --max-fee=1
bos rebalance --amount=50000 --in=<node with inbound liquidity>
bos rebalance ---in=<node with inbound liquidity> 
```

Everything results in:

```
err:
  - 400
  - NoInboundChannelIsAvailableToReceiveRebalance
```

I've tried with multiple different public keys. Other various bos commands seem to work. Any ideas?

**Comment by alexbosworth** [comment]
Make sure you have an active channel with that peer that has inbound liquidity

**Comment by josephtyler** [comment]
I've tried a few different active channels with over 1M+ in inbound liquidity.

**Comment by alexbosworth** [comment]
The error indicates it doesn't see an active channel with sufficient inbound, or you banned the peers using global avoid

**Comment by scarolan** [comment]
Same issue here.  Using version 11.40.0.  Raspberry Pi 4 running Raspiblitz with tor v3.

Plenty of remote balance on one of my channels, and several channels with only local balance.

**Comment by alexbosworth** [comment]
Need more details - can't repo

Try joining the telegram group if you want one on one help

**Comment by scarolan** [comment]
Sure thing @alexbosworth.  For the record I think this is probably an lnd thing - am looking in the logs to see if I can find an error message.
