### ISSUE TITLE
Fails to rebalance automatically

### ISSUE THREAD

**Issue by darioAnongba** [alexbosworth/balanceofsatoshis#139]
Hi @alexbosworth,

**Description**
I'm currently running a routing node with Umbrel and I'm using different tools to keep my channels healthy. One of the most recommended tools to rebalance is this repo. My goal would be to run the `bos rebalance` script in a cron job every X amount of time to check if a cheap rebalance is available.

I noticed that some well-known nodes on the network have this approach. Given that new channels are created all the time and the fees are not updated instantly, these nodes check the network constantly and quickly rebalance before the channel fees are updated. I know this is true because I often create new channels and update the fees every 30min in a cron-job using `charge-lnd`. Most of the time, some nodes like `Coingate` quickly rebalance before my cron job runs.

So ideally, for this tool to be used as I expect, I should be able to run `bos rebalance` without any options (with some config) to check if a rebalance is possible. The tool should work from time to time.

**My node**

My node is a T1 node (by your own scoring system) with currently 57M inbound and 68M outbound. I route transactions every day and have 31 active channels: [see here](https://amboss.space/node/033323c3b00f142cff4fd2e20e125112d0c58ae4a3cc135f4e57512652050a4c05)

**Problem**

No matter what I do or in what state my channels are, the script always returns. 
```
err: 
  - 400
  - NoInboundChannelIsAvailableToReceiveRebalance

```
but that shouldn't be the case as I have plenty of channels with inbound liquidity. The tool should be able to find a route easily, maybe it will be expensive to perform the rebalance but saying that there are not channels available is either a bug or poor phrasing on the error message. Since I don't expect this to bug, I think I may have a problem somewhere.

**Current behavior**

Rebalancing never works and fails with `NoInboundChannelIsAvailableToReceiveRebalance`

**Expected behavior**

Run the script in a cron job to perform rebalances without having to manually select nodes (in and out).

**Comment by alexbosworth** [comment]
The problem is the fee most likely, by design it is requiring opt in to paying significant fees otherwise automate rebalance can easily mean automate losing money

**Comment by darioAnongba** [comment]
Hi! Thanks for the reply, I also tried setting a ridiculously high `max-fee` and `max-fee-rate` just to see if it works (didn't care about losing money) and the result is always the same, not matter what I do.

```
rebalance --amount 50000 --max-fee-rate 12000 --max-fee 40000

err: 
  - 400
  - NoInboundChannelIsAvailableToReceiveRebalance

```

**Comment by alexbosworth** [comment]
OK there are other considerations as well, like there is plenty of inbound liquidity on a channel to be used for inbound and the peers are connected

One thing that might help is also using the tag system, you can select nodes you want to be used for --in in `bos tags` and then do a rebalance with `--in <tagname>`
