### ISSUE TITLE
[telegram] `bos telegram` sends channel was closed message when pool abandons a channel

### ISSUE THREAD

**Issue by benthecarman** [alexbosworth/balanceofsatoshis#140]
I didn't have a channel with a peer, and a channel was being opened with pool. It did an `abandon` channel and sent me a message that the channel was closing.

**Comment by alexbosworth** [comment]
this is relaying a message from lnd so it's an lnd level event being reflected

**Comment by alexbosworth** [comment]
duplicate of #114
