### ISSUE TITLE
problem with bos forwards and bos accounting forwards

### ISSUE THREAD

**Issue by Quenos** [alexbosworth/balanceofsatoshis#143]
If I execute bos accounting forwards --rate-provider coindesk
The function works as expected

If I execute bos forwards --days 14
The function works as expected

But if I execute first bos forwards --days 14 and then bos accounting forwards --rate-provider coindesk
The latter will return 'null' till after either a reboot or a new forward has been made

**Comment by alexbosworth** [comment]
it doesn't really make sense considering the commands are stateless
