### ISSUE TITLE
[inbound-channel-rules]: Add variable for private channel status

### ISSUE THREAD

**Issue by alexbosworth** [alexbosworth/balanceofsatoshis#163]
To allow for logic in inbound channel rules that is specific to incoming channel private or public status, add a variable that reflects this status

**Comment by daldwinc** [comment]
In my ideal scenario, I could set different minimum channel sizes for inbound channels based on the channel type:

`if type=private then min.chansize = 10000 sats, else min.chansize = 5000000 sats`

**Comment by alexbosworth** [comment]
this is now supported, if(private, capacity >= 20*k, capacity >= 5*m)
