### ISSUE TITLE
[fees:] to support --tag

### ISSUE THREAD

**Issue by BhaagBoseDK** [alexbosworth/balanceofsatoshis#170]
bos fees should support --tag for selection
this would help in reviewing narrowed down peer list and will be consistent with other bos commands.

**Comment by alexbosworth** [comment]
it does support tags in the `--to` flag

**Comment by BhaagBoseDK** [comment]
yes I know but that requires changing fees. 
the use case is to review the fee policies on
bos fees --tag high_drain_nodes
bos fees --tag prefer_to_keep_remote
etc

**Comment by alexbosworth** [comment]
It doesn't require changing fees

**Comment by BhaagBoseDK** [comment]
Thanks. It works!
