### ISSUE TITLE
503,UnexpectedErrorGettingCertFileData,[object Object]

### ISSUE THREAD

**Issue by n8hanwilliams** [alexbosworth/balanceofsatoshis#171]
I get this error no matter what I try and do; however, when I do "bos utxos" it gives me a little more detail. Any insight would be greatly appreciated!

```
err:
  - 503
  - UnexpectedErrorGettingCertFileData
  -
    err:
      message: ENOENT: no such file or directory, open '/home/umbrel/.lnd/tls.cert'
      stack:
        - Error: ENOENT: no such file or directory, open '/home/umbrel/.lnd/tls.cert'
```

**Comment by n8hanwilliams** [comment]
Wow you're fast! Hmm, my username is umbrel

**Comment by n8hanwilliams** [comment]
Ah, I'm dumb. I see what you were saying - I was logged in as "root". I'm good to go now. Thanks so much! Looking forward to using your tool!

**Comment by alexbosworth** [comment]
well somehow it doesn't recognize your install as umbrel and on umbrel the cert file is not on the default location so you have to tell it the location via saved nodes feature that you can read in the readme

**Comment by morrisonbrett** [comment]
Can you please share a link to where the 'saved nodes' feature you refer to is?

**Comment by alexbosworth** [comment]
https://github.com/alexbosworth/balanceofsatoshis#saved-nodes

**Comment by morrisonbrett** [comment]
Cool. I got it working. I had to modify my alias for `bos` and `bosd` to include the network and paths as you specified: https://github.com/alexbosworth/balanceofsatoshis/blob/55b88eb55c366941c4eb5ffdfdbbec2d2385c44f/README.md?plain=1#L502
