### ISSUE TITLE
bos credentials --cleartext returns every time different macaroon value 

### ISSUE THREAD

**Issue by MykelSIlver** [alexbosworth/balanceofsatoshis#207]
To begin: It is not a bug, but I am curious why the following is happening. 

Each time bos credentials --cleartext returns a different value of macaroon. Surprisingly this is a valid encrypted value because using this value results in no failure.

When i do manually a base64 -w0 admin.macaroon it returns every time the same encrypted value.

I looked at the code but I couldn't find why the bos credentials --cleartext returns every time a different encrypted value of macaroon.

Hope anyone can clear this up for me? 

Thanks in advance.

**Comment by alexbosworth** [comment]
It is time-restricting the validity of the macaroon produced and time is always changing

**Comment by MykelSIlver** [comment]
Thanks for the clarification.
