### ISSUE TITLE
autostart only works if invoked manually, but not when restarting

### ISSUE THREAD

**Issue by mac-city** [alexbosworth/balanceofsatoshis#211]
thanks for this amazing script!  everything seems to work perfect except autostarting the telegram connection.

if I issue the command: sudo systemctl start bos-telegram.service it works because sudo systemctl status bos-telegram.service shows signs and telegram reports it's connected but if I restart my little raspberrypi umbrel, it doesn't start.  do I perhaps need to tweak the 
TimeoutSec=120
RestartSec=30
settings?

**Comment by alexbosworth** [comment]
did you try `systemctl enable bos-telegram`

**Comment by mac-city** [comment]
well, no I didn't.  I'm surprised I can get anything to work if I missed that little tidbit from the instructions, but I see it now, lol.  btw, what took so long to answer my question.  I asked it over 3 minutes ago, lol.  off to try a restart.  do you know what else I can't find on the code or wiki?  where to send lightning tips 😉

**Comment by mac-city** [comment]
of course, that fixed it.  thank you!  as a new umbrel node runner, would you recommend that I should consider installing your other scripts posted here, or are some of them not necessary if running BOS?

**Comment by alexbosworth** [comment]
what are the other scripts? I guess check out what works for you really, I personally just use the bos scripts

**Comment by mac-city** [comment]
ln-service, ln-accounting, goldengate

**Comment by alexbosworth** [comment]
those are all like component libraries you can't really run them on their own
