### ISSUE TITLE
Satoshi unit on telegram bot messages

### ISSUE THREAD

**Issue by bota87** [alexbosworth/balanceofsatoshis#219]
What about showing the amount in satoshi instead of bitcoin?

Current
💰 Forwarded 0.00100002 NodeA → NodeB. Earned 0.00000007 0.01% (60)
⛓ (pending) Received 0.01069142

Suggested
💰 Forwarded 100,002 sats NodeA → NodeB. Earned 7.202 sats 0.01% (60)
⛓ (pending) Received 1,069,142 sats

**Comment by alexbosworth** [comment]
It is shown as satoshis, just ignore the zeros to the left

**Comment by alexbosworth** [comment]
I think it's something you can get used to if it's consistent

**Comment by asvdf** [comment]
I actually agree with OP, for what it's worth, arguments being:

1. readability
2. less chars in TG messages
3. future proofing, as whole BTCs will be more and more rare (already are not a thing in LN anyway) while msats will be more and more worthy

Just flying opinions.

**Comment by bota87** [comment]
@asvdf I followed your advice and made a [fork](https://github.com/bota87/balanceofsatoshis), for now I changed only the "forwarded" message.

Anyway I think that a better approach can be add a parameter to the telegram command (something like --use-satoshis) so anyone can choose is preference.

@alexbosworth it's fine for you if I try to make a pull request for that?

**Comment by alexbosworth** [comment]
sure

**Comment by asvdf** [comment]
> Anyway I think that a better approach can be add a parameter to the telegram command (something like --use-satoshis) so anyone can choose is preference.

this is actually a smart approach! makes everyone happy

**Comment by bota87** [comment]
@alexbosworth thank's for having fast merged the PR!

Do you think that I can propose a new one to show even the millisats on the "forwarded" message when the `--use-small-units` option is set?

Some users on [PLEBNET](https://t.me/plebnet), even me, ask for that

**Comment by alexbosworth** [comment]
sure ok

**Comment by bota87** [comment]
@alexbosworth thank's for the fast merge, as usual!
Do you forgot to bump up the ln-telegram/balanceofsatoshis version or just waiting for something else?

**Comment by alexbosworth** [comment]
Ah I thought maybe you were going to put up a PR for that, I can look at it in a bit though
