### ISSUE TITLE
[peers] : support --active-days to get a list of peers from which routes were received in n days

### ISSUE THREAD

**Issue by BhaagBoseDK** [alexbosworth/balanceofsatoshis#269]
bos peers --idle-days 30 gives a list of peers from which no routes were received in the last 30 days. 

an analogous call could be 

bos peers --active-days 30 gives a list of peers from which routes were received in last 30 days

bos forwards can be used for similar query but bos forwards does not support --tag option.

**Comment by alexbosworth** [comment]
you can use `bos peers --fee-days 30` for routing activity

**Comment by BhaagBoseDK** [comment]
can it exclude those with zero fee earned?

**Comment by alexbosworth** [comment]
You could sort `--sort fee_earnings`

**Comment by BhaagBoseDK** [comment]
thanks
