### ISSUE TITLE
[chart-fees-paid]: Add alias support to --out and --in

### ISSUE THREAD

**Issue by alexbosworth** [alexbosworth/balanceofsatoshis#272]
Currently out and in flags require a public key, but if it's a peer it could also accept an alias match

**Comment by niteshbalusu11** [comment]
`chart-fees-paid`is taking an array of lnds as input, what would happen in this scenario where one saved node is peered with yalls-clearnet and another one with yalls-tor and you run the command `bos chart-fees-paid --out yalls`

`findKey` would find it for both, array length more than, then error out?

**Comment by alexbosworth** [comment]
Yeah that is an issue, I think that's a good solution though

**Comment by niteshbalusu11** [comment]
Cool ok.
