### ISSUE TITLE
[telegram] Add ability to /restore from channel backup

### ISSUE THREAD

**Issue by morrisonbrett** [alexbosworth/balanceofsatoshis#280]
On Telegram, /backup works great, and of course posts a .backup file in the Telegram chat.

Would be great to have a new feature /restore, and prompt for a .backup file and have it restore all the channels AND the LND config.

My scenario is this. I have an Umbrel (Node A) working with 18 open channels. I have a new Umbrel (Node B) up with a faster Raspberry Pi and faster storage.  Would be great if I could do a Backup on A, shut down A, and then /restore on B, all using Telegram BOS.

One challenge would be if A was then re-started there would be protocol errors as they're both claiming to be the same node. That challenge I imagine is already handled in lnd and probably out of scope for this request.

**Comment by alexbosworth** [comment]
The backup file is intended for emergency restoration and isn't a consistent backup of all data

If you want to move a node to a different device there is a guide here: https://github.com/lightningnetwork/lnd/blob/master/docs/safety.md#migrating-a-node-to-a-new-device

**Comment by morrisonbrett** [comment]
I understand. It would be really useful though if it was a consistent backup and you could do an atomic restore. Understand if the scope is outside BOS and if you want to close this issue out.

**Comment by alexbosworth** [comment]
Channels are updating quite a lot, plus lnd doesn't offer this type of API control, so yeah it would not really be super feasible in telegram
