### ISSUE TITLE
[limit-forwarding] - add --restrict-out inKey/OutKey

### ISSUE THREAD

**Issue by alexbosworth** [alexbosworth/balanceofsatoshis#289]
If you want to make sure that inbound liquidity from node A only leaves out node B, you would specify `--restrict-out nodeAKey/nodeBKey`

Then when a forward is attached from nodeA, if it's not going to node B, reject it

**Comment by laurentdebricon** [comment]
could you do : 
   - node A only to everything
   - everything to node B only

**Comment by alexbosworth** [comment]
Implemented as `--deny` now
