### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by davidepatti** [alexbosworth/balanceofsatoshis#299]
I've just experienced the above error when trying to open a dual funded channel.
I solved by running the following export:
`export NODE_OPTIONS=--openssl-legacy-provider`

I don't know if it was a problem of bos or nodejs, but I wanted to report this just in case someone else gets the same error.
My environment is:
bos 12.7.0
nodejs 17.9.0 (current latest)
rasblitz node 1.7.2

**Comment by alexbosworth** [comment]
please try node LTS 16.15.0?

**Comment by davidepatti** [comment]
Dear Alex, as I said I solved by running the export, so I'll try the next time I'm the same situation of opening the dual funded channel. All the other things worked.

**Comment by alexbosworth** [comment]
ok if that works for you long term that is great

this is an issue upstream in nodejs with tls support so hopefully that gets fixed in the latest-features nodejs

**Comment by davidepatti** [comment]
perfect, thank you for the clarification.

**Comment by alexbosworth** [comment]
this should be addressed now
