### ISSUE TITLE
Error: NoOutboundPeerWithSufficientBalance

### ISSUE THREAD

**Issue by PrinzMonty** [alexbosworth/balanceofsatoshis#303]
I don't understand this, no matter which channel I rebalance, it always comes up with this message. Does anyone have an idea?

```
err:
  - 404
  - NoOutboundPeerWithSufficientBalance
```

**Comment by alexbosworth** [comment]
what's the exact command you are trying?

you have local balance with the peer?

**Comment by PrinzMonty** [comment]
I try for test:

`bos --node <MY_NODE_NAME> rebalance --in <PEER1> --out <PEER2> --max-fee-rate 1`

peer1: remote 90000 Sats and local 0 Sats
peer2: remote 5335 Sats and local 91000 Sats

**Comment by alexbosworth** [comment]
If you are putting `out` it means the rebalance goes out that peer, meaning the payment spends funds you have in local balance with that peer

If the local balance is zero, it cannot pay out that peer and in to the other peer, so it will fail

**Comment by PrinzMonty** [comment]
Yes, but the error also occurs when I try with peers that have both local and remote balance.

**Comment by alexbosworth** [comment]
ah ok, maybe the amount is too small, rebalance is not meant for very small amounts but you can also try specifying an amount

**Comment by PrinzMonty** [comment]
Ok. And when is the amount too small? Is there any rule?

**Comment by alexbosworth** [comment]
50k would be the minimum

**Comment by PrinzMonty** [comment]
Ok, one last question before I go any further. Do I have to have a channel that contains more than 50k Sats on both sides?

**Comment by alexbosworth** [comment]
the outbound side should have 50k and the inbound side should have remote balance of 50k, since you are paying the funds from out into in

**Comment by PrinzMonty** [comment]
Okay, thanks for the clarification!

I think then we can close the Issue, since it is a user error and not a program error ;)

**Comment by PrinzMonty** [comment]
I'm afraid I'll have to ask for help again. I thought I understood what the "outbound" and "inbound" capacity was all about. Now when I try to rebalance with BOS, the error still occurs:

![image](https://user-images.githubusercontent.com/4109582/167252031-db45d64f-b420-4f36-9778-619f2da84376.png)

I finally have enough Outbound Balance... or not?

**Comment by alexbosworth** [comment]
There are some hidden balance elements like commitment tx fee and reserve amount

In general I wouldn't use rebalance for very small amounts, for that I would use `bos send` instead and send to your own public key specifying in and out, there is no limit there
