### ISSUE TITLE
Funds "pending" after failed open-balanced- channel

### ISSUE THREAD

**Issue by Fogelman1982** [alexbosworth/balanceofsatoshis#314]
Wanted to open my first dual funded channel and unfortunately one of the transactions was "booted" from the mempool which leads to "Transaction invalid: some outputs that it attempts to spend have been already spent or are no longer valid" (blockchain.com) although the funds are missing from wallet and the channel is shown as "pending" (RTL and Thunderhub)

The person at the other peer said something about "looks like my wallet spent the input after it was booted, and I think you can recover your funds wiht "bos open-balanced-channel ---recover" - but this does not work...

Any thoughts?

(Im runing Umbrel on Debian Virtual box)

**Comment by alexbosworth** [comment]
It shows you a refund tx, put `bos broadcast <refundtx>`

**Comment by Fogelman1982** [comment]
Thanks for your reply. So if i understand you correctly I should just run the command "bos broadcast (hash)" (where hash is the transaction that is shown as invalid) ?

**Comment by alexbosworth** [comment]
Maybe it would help if you revealed more information, I can't be specific without knowing more about what happened

**Comment by Fogelman1982** [comment]
Here is the transaction : ae35d9f2ca0051372510ffc5d21c585dd62a1c358476c2e095c09e84668e30c5, maybe thats enough information?

**Comment by alexbosworth** [comment]
so you didn't send any coins on chain?

**Comment by Fogelman1982** [comment]
Nope.

**Comment by alexbosworth** [comment]
ok so if you didn't send any coins on chain, how are there any coins to recover?

**Comment by Fogelman1982** [comment]
Funds are stuck in a pending open channel and not shown in our Bitcoin core or Umbrel dashboard.

**Comment by alexbosworth** [comment]
are you still running the open-balanced-channel command?

**Comment by Fogelman1982** [comment]
I don´t know what to respond to that... I did that this friday and dont know if thay means its still running?

**Comment by alexbosworth** [comment]
If you started the command and it's still running, exit out of the command so that the funds can be unlocked

**Comment by alexbosworth** [comment]
I'm not sure what you are seeing, do you still see the output of the command? You can do `bos utxos` to confirm you have a locked UTXO

**Comment by Fogelman1982** [comment]
I really appriciate your help, will have to check tomorrow as i have no possibility to run the commands now. Thanks for now, will get back to you after bos utxos :)

**Comment by Fogelman1982** [comment]
> I'm not sure what you are seeing, do you still see the output of the command? You can do `bos utxos` to confirm you have a locked UTXO

I ran the bos utxo and found one tx with correct amount and tried the "box open-balances-channel --recover" with the hex format of the tx and it worked! Showed something about "Err:400" but also "recovercomplete".

Thanks a lot for your help!

**Comment by alexbosworth** [comment]
OK good to hear it recovered

Next time another option is to use `bos broadcast` with the channel open transaction and it will keep rebroadcasting the transaction until it enters the mempool

**Comment by alexbosworth** [comment]
There is also a fully formed refund tx that is shown at the start, you can use that with `bos broadcast` too if something goes wrong

**Comment by alexbosworth** [comment]
use the --recover flag if you see funds were sent to an address and the open failed
