### ISSUE TITLE
Question: Working with two channels to the same public node, one private one announced.

### ISSUE THREAD

**Issue by brianoflondon** [alexbosworth/balanceofsatoshis#321]
I'm struggling a bit with trying to move sats around and specify which channel to use.

Most of the tools in BOS seem to require a public node address or alias but for this case I really need to give a specific channel in the `--out` field because of my two connections.

I'm trying to move sats OUT through the PUBLIC channel not the PRIVATE one. I've tried to use the `--avoid` option with the channel ID of the channel I DON'T want to use.

This is also made complicated by my having a public channel to the node I'm trying to send funds to (and if I don't specify --out that channel will always be used of course).

Am I missing some option that lets me decided which CHANNEL to use for a specific payment rather than which connected node/peer?

It seems that any time I use the `--avoid` option I get:

```
err: 
  - 503
  - UnexpectedSendPaymentFailure
 ```

**Comment by alexbosworth** [comment]
Specifying a channel for a payment is not supported

**Comment by brianoflondon** [comment]
> Specifying a channel for a payment is not supported

Is this technically feasible?

I guess it's somewhat unusual to have ended up with 3 channels to the same node but that's what I've got.

**Comment by alexbosworth** [comment]
You could try `bos call pay` and specify an outgoing channel id there

I'm not sure of the full use case to say what is possible and not

**Comment by brianoflondon** [comment]
Thanks. I'm phasing out using private channels so this is less of an issue for me.
