### ISSUE TITLE
[funds safety] keep backup log of refund txns shown on stdout

### ISSUE THREAD

**Issue by GordianLN** [alexbosworth/balanceofsatoshis#323]
e.g. during a balanced open, if something goes wrong and the user didn't note the refund tx, plus the terminal was closed/screen was cleared, funds might be lost.
Having all txns saved in an incremental `bos_refund_txns.log` file, with nice comments, like:
```
balanced open <capacity> N sats/vb with <pubkey>:
<refundtxn>

...
```

would constitute a nice, probably very easy to implement, failsafe mechanism.

**Comment by alexbosworth** [comment]
Funds would not be lost, the refund tx can be regenerated even if you save nothing using the `--recover` flag

**Comment by alexbosworth** [comment]
Also open-group-channel mechanism does not need a refund as the funding there is atomic with the channel
