### ISSUE TITLE
bos probe didn't work on docker

### ISSUE THREAD

**Issue by bota87** [alexbosworth/balanceofsatoshis#334]
Probably it's just a problem with my setup but I can't make bos probe works with any of my peers. 
```
bos probe **** -v
checking_for_path_to: ****
attempted_paths: 0
```

with the --find-max options things are better but I can't see the latency that is the reason why I'm probing the nodes
```
bos probe **** --find-max
probing: **** ****
probing:
  - ****x0 ★ ★ ★ ★
  - **** ****. Fee rate: 0.00% (0)
evaluating: 968012
evaluating: 1452018
evaluating: 1905774
total_liquidity: 0.01905775
```
I've tried the verbose option to debug the problem but I don't see anything usefull

**Comment by alexbosworth** [comment]
did you try altering the amount on bos probe?

**Comment by bota87** [comment]
I tried to set the amount to 1 but get the same result, now I tried with 1000 and it's working!
Thank you
