### ISSUE TITLE
donation link not showing in terminal

### ISSUE THREAD

**Issue by RemoRitzmann** [alexbosworth/balanceofsatoshis#337]
I updated with: bos@raspberrypi:~ $ npm install -g npm@8.13.2 on raspiblitz terminal after typing "bos"
it then tells me: 11 packages are looking for funding, run `npm fund` for details

bos@raspberrypi:~ $ npm fund
bos

So I tried: bos@raspberrypi:~ $ npm fund bos
but got this error:
npm ERR! code ENOFUND
npm ERR! No valid funding method available for: bos

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bos/.npm/_logs/2022-07-10T08_42_47_424Z-debug-0.log

Should it not lead me to your donation webpage?

**Comment by alexbosworth** [comment]
npm fund is part of npm not bos so no
