### ISSUE TITLE
[remove-peer] Why is `--fee-rate` ignored?

### ISSUE THREAD

**Issue by hieblmi** [alexbosworth/balanceofsatoshis#338]
`bos remove-peer` was specified with `--fee-rate 1` and then printed `fee_rate:          1` as confirmation but the closing transaction was published with 3.65 sat/vbyte. Is this due to the policy of the remote party or why isn't the closing fee as specified?

**Comment by alexbosworth** [comment]
lnd doesn't use the provided fee so this is an lnd issue
