### ISSUE TITLE
fund not return after bos channel closed 

### ISSUE THREAD

**Issue by LStratos** [alexbosworth/balanceofsatoshis#340]
Hi all,
need some advise.
the case is like that
sometime ago, we was opening a 1mil balance channel using bos.
everything was going well all the way till broadcasting pending.
after my friend took a closer look and notice that the channel was not broadcasted.
the channel was in a status "opening" for something hence we decided to close. [ pls refer to the image below
![image](https://user-images.githubusercontent.com/16865519/178385901-421239b6-ed65-40e1-af75-815cb534a44b.png)
![image](https://user-images.githubusercontent.com/16865519/178385999-8f68c901-3ff9-4466-a189-5894fbed73ac.png)

the buddy fund was return but mine was not return.
On closer checking, i found the following,
the 500k sat was not withdrawn but the fee of 840sat was withdrawn (refer to the image before)
![image](https://user-images.githubusercontent.com/16865519/178386123-edfad26a-1ed5-4ac8-8859-1058c47dc032.png)
I check there is not fund in limbo.
![image](https://user-images.githubusercontent.com/16865519/178386331-ca9bc302-612f-41e0-a97d-b369491b2085.png)
![image](https://user-images.githubusercontent.com/16865519/178386548-6f81fed0-8319-4323-9214-6b4481440a67.png)

i suspect the 500K sat could be stuck some where in my node and i am not sure how to recovery it. 

*extra noted:
we run the lncli abandonchannel command in Lndterminal to close the channel.

From:
A newbie node owner in a panic mode T.T

**Comment by alexbosworth** [comment]
Did you try the refund tx

**Comment by LStratos** [comment]
what to run? 
can you guide me on it

**Comment by alexbosworth** [comment]
Do you have the original output from when you ran the command originally?

**Comment by LStratos** [comment]
bos or the lncli abandonchannel command

**Comment by alexbosworth** [comment]
bos command

**Comment by LStratos** [comment]
i believe my buddy is using the bos open-balanced-channel with my pub key

**Comment by alexbosworth** [comment]
if you look in the list of chain transactions do you see a chain transaction that matches funding this channel

**Comment by LStratos** [comment]
base on the bos utxos coomand. i took the outpoint and search it in mempool and found it match with the amount 500K plue the 380 fee

Bos utxos command
![image](https://user-images.githubusercontent.com/16865519/178390164-39da2255-9f78-46ed-8885-0d9defc68bca.png)

mempool
![image](https://user-images.githubusercontent.com/16865519/178389756-11e6fb42-1f91-43a9-a983-404dce2bdf8c.png)

**Comment by LStratos** [comment]
noted. will try

how did you get this data string?
02000000000102e6da1c16a88994a953f57b42f43596b7432e6bf30ca00a5d3742c9f4904083680000000000ffffffff205128a9121203867014ffa3705b0b8d7e934ceaebd6a3bb6f5646b4791e1ecf0100000000ffffffff027f5c01000000000016001438cc25e73abdbc5320b3ec469061788a3b662f409ca2070000000000160014fa82692f4a7d8066aaec65825ad58bba20e232c0024730440220159083465d7140d86d1c5ddaf3b77a9ec4ce0a14e25766bc3a6f81daca35ea2c02201f07557240f41e6199b55363a9637d6e6b9eb7f5884ec58b07dfa1ba35183ecc012102757de79a88a449c06b3285bb3114ea590976c8baebcfc6606597da8bcf5b19b602483045022100cdd54dc41502a5be6e1756571644b949a3d62d67e970e0af31a62d1add6a682502207878557dff12307712483b14c75eb3358eb21a11244f089f26da5193d6a356d90121032558a30bec345fadc38a2162d5de88d6dfbeee86e0adc1b10e2bdbbbef42cc2600000000

**Comment by LStratos** [comment]
i see my fund now.
thank you so much. T.T 
will all stuck fund from channel closure be able to use this?

**Comment by alexbosworth** [comment]
are there more stuck funds?

next time if you look at the output of the command it will show you a "refund transaction" at the top, if you hold on to that transaction you can run `bos broadcast` or use any other broadcast tool and get your funds back if something goes wrong

also, I would try `bos call deletependingchannel` instead of abandonchannel unless you know what you are doing, abandonchannel does not check if the channel can be safely deleted

**Comment by LStratos** [comment]
nice 
new lesson learn for me
thank you once again for the guide and help

**Comment by LStratos** [comment]
refer to this comment by alexbosworth
https://github.com/alexbosworth/balanceofsatoshis/issues/340#issuecomment-1181219986

additional info on how to close stuck channel by alexbosworth
https://github.com/alexbosworth/balanceofsatoshis/issues/340#issuecomment-1181224858
