### ISSUE TITLE
[telegram] bos telegram starts with TypeError crash

### ISSUE THREAD

**Issue by ChuckNorrison** [alexbosworth/balanceofsatoshis#411]
After successful setup bos on my raspiblitz, i started to test the telegram feature. It works great till a second telegram user finds the bot and starts writing commands. Now the bot starts to crash after it gets restarted.

bos version is 12.35.0

> Sep 25 19:51:15 raspberrypi bos[1618009]: connecting_to_telegram:
> Sep 25 19:51:15 raspberrypi bos[1618009]:   (empty array)
> Sep 25 19:51:32 raspberrypi bos[1618009]: is_connected: true
> Sep 25 19:51:34 raspberrypi bos[1618009]: /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/context.js:326
> Sep 25 19:51:34 raspberrypi bos[1618009]:         return this.api.sendMessage(orThrow(this.chat, "sendMessage").id, text, other, signal);
> Sep 25 19:51:34 raspberrypi bos[1618009]:                     ^
> Sep 25 19:51:34 raspberrypi bos[1618009]: TypeError: Cannot read properties of undefined (reading 'api')
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at reply (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/context.js:326:21)
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at asyncAuto.checkAccess (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-telegram/authentication/check_access.js:35:11)
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at runTask (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:293:13)
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:233:31
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at processQueue (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:243:13)
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at taskComplete (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:259:9)
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:286:17
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at validate (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-telegram/authentication/check_access.js:29:16)
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at runTask (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:295:13)
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:233:31
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at processQueue (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:243:13)
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at auto (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:230:5)
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-telegram/authentication/check_access.js:18:12
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at new Promise (<anonymous>)
> Sep 25 19:51:34 raspberrypi bos[1618009]:     at module.exports (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-telegram/authentication/check_access.js:17:10)

**Comment by alexbosworth** [comment]
What commands?

**Comment by ChuckNorrison** [comment]
> What commands?

it starts to crash with `/connect 123` for example

**Comment by alexbosworth** [comment]
ok i'll take a look

**Comment by alexbosworth** [comment]
ok please try updating and see if you encounter the same issue

**Comment by ChuckNorrison** [comment]
The bot does not crash anymore, thanks a lot :)

Some outputs:

> 
> Sep 25 20:30:03 raspberrypi bos[1742410]: connecting_to_telegram:
> Sep 25 20:30:03 raspberrypi bos[1742410]:   (empty array)
> Sep 25 20:30:11 raspberrypi bos[1742410]: is_connected: true
> Sep 25 20:30:12 raspberrypi bos[1742410]: err:
> Sep 25 20:30:12 raspberrypi bos[1742410]:   message: Call to 'sendMessage' failed! (403: Forbidden: bot was blocked by the user)
> Sep 25 20:30:12 raspberrypi bos[1742410]:   stack:
> Sep 25 20:30:12 raspberrypi bos[1742410]:     - GrammyError: Call to 'sendMessage' failed! (403: Forbidden: bot was blocked by the user)
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at toGrammyError (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/core/error.js:35:12)
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at ApiClient.callApi (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/core/client.js:86:48)
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at async /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/telegram/start_telegram_bot.js:440:13
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at async /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/composer.js:483:13
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at async /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/composer.js:61:13
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at async /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/composer.js:483:13
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at async /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/composer.js:61:13
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at async /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/composer.js:483:13
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at async /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/composer.js:61:13
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at async /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/composer.js:483:13
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at async /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/composer.js:61:13
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at async /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/composer.js:483:13
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at async /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/composer.js:61:13
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at async /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/composer.js:483:13
> Sep 25 20:30:12 raspberrypi bos[1742410]:     -     at async /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grammy/out/composer.js:61:13
> Sep 25 20:30:54 raspberrypi bos[1742410]: err:
> Sep 25 20:30:54 raspberrypi bos[1742410]:   - 401
> Sep 25 20:30:54 raspberrypi bos[1742410]:   - CommandRequiresConnectCode
> Sep 25 20:31:05 raspberrypi bos[1742410]: err:
> Sep 25 20:31:05 raspberrypi bos[1742410]:   - 401
> Sep 25 20:31:05 raspberrypi bos[1742410]:   - CommandRequiresConnectCode
> Sep 25 20:31:16 raspberrypi bos[1742410]: err:
> Sep 25 20:31:16 raspberrypi bos[1742410]:   - 401
> Sep 25 20:31:16 raspberrypi bos[1742410]:   - CommandRequiresConnectCode

Would be great if the 401 would send a message for missing authentication. Anyway, iam fine
