### ISSUE TITLE
bos report returns ExpectedArrayOfTagsToGetForwardingRecords

### ISSUE THREAD

**Issue by khashmeshab** [alexbosworth/balanceofsatoshis#413]
The `bos report` command returns this after updating to the latest version:
```
- 400
- ExpectedArrayOfTagsToGetForwardingRecords
```

**Comment by alexbosworth** [comment]
OK try updating

**Comment by khashmeshab** [comment]
Thank you. Now this error shows up:
`
- 503
- ExpectedPaymentPathInRpcPaymentDetails

`

**Comment by alexbosworth** [comment]
doh, interesting, I will take a look

**Comment by alexbosworth** [comment]
OK try updating?

**Comment by khashmeshab** [comment]
Thank you. Works as great as always.
