### ISSUE TITLE
[telegram] failed_to_connect crashes

### ISSUE THREAD

**Issue by ChuckNorrison** [alexbosworth/balanceofsatoshis#414]
My bos telegram instance starts crashing randomly with failed_to_connect. Maybe this can be hardened to stop crashing?

> Sep 28 01:06:51 raspberrypi systemd[1]: Started Balance of Satoshis Telegram Bot.
> Sep 28 01:06:59 raspberrypi bos[1645000]: err: failed_to_connect
> Sep 28 01:06:59 raspberrypi bos[1645000]: err:
> Sep 28 01:06:59 raspberrypi bos[1645000]:   message: 503,GetWalletInfoErr,[object Object]
> Sep 28 01:06:59 raspberrypi bos[1645000]:   stack:
> Sep 28 01:06:59 raspberrypi bos[1645000]:     - Error: 503,GetWalletInfoErr,[object Object]
> Sep 28 01:06:59 raspberrypi bos[1645000]:     -     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/asyncify.js:105:61
> Sep 28 01:06:59 raspberrypi bos[1645000]:     -     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> Sep 28 01:06:59 raspberrypi bos[1645000]: Error
> Sep 28 01:06:59 raspberrypi bos[1645000]:     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@alexbosworth/caporal/lib/command.js:486:46
> Sep 28 01:06:59 raspberrypi bos[1645000]:     at tryCatcher (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/util.js:16:23)
> Sep 28 01:06:59 raspberrypi bos[1645000]:     at Promise._settlePromiseFromHandler (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:547:31)
> Sep 28 01:06:59 raspberrypi bos[1645000]:     at Promise._settlePromise (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:604:18)
> Sep 28 01:06:59 raspberrypi bos[1645000]:     at Promise._settlePromise0 (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:649:10)
> Sep 28 01:06:59 raspberrypi bos[1645000]:     at Promise._settlePromises (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/promise.js:725:18)
> Sep 28 01:06:59 raspberrypi bos[1645000]:     at _drainQueueStep (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:93:12)
> Sep 28 01:06:59 raspberrypi bos[1645000]:     at _drainQueue (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:86:9)
> Sep 28 01:06:59 raspberrypi bos[1645000]:     at Async._drainQueues (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:102:5)
> Sep 28 01:06:59 raspberrypi bos[1645000]:     at Immediate.Async.drainQueues [as _onImmediate] (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/bluebird/js/release/async.js:15:14)
> Sep 28 01:06:59 raspberrypi bos[1645000]:     at processImmediate (node:internal/timers:466:21)
> Sep 28 01:06:59 raspberrypi systemd[1]: bos-telegram.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> Sep 28 01:06:59 raspberrypi systemd[1]: bos-telegram.service: Failed with result 'exit-code'.

**Comment by alexbosworth** [comment]
It's by design that it doesn't start if it can't connect to the node
