### ISSUE TITLE
[telegram] randomly crashes with htlc event 

### ISSUE THREAD

**Issue by ChuckNorrison** [alexbosworth/balanceofsatoshis#417]
Iam running bos version 11.50.0 on my raspiblitz. Iam using telegram bot and recognized a frequently connected message. This message is related to this crash:

> Oct 17 10:50:22 raspberrypi bos[263011]: - 503
> Oct 17 10:50:22 raspberrypi bos[263011]: - ErrorInPaymentsSub
> Oct 17 10:50:22 raspberrypi bos[263011]: -
> Oct 17 10:50:22 raspberrypi bos[263011]:   err:
> Oct 17 10:50:22 raspberrypi bos[263011]:     - 503
> Oct 17 10:50:22 raspberrypi bos[263011]:     - UnexpectedPastPaymentsErr
> Oct 17 10:50:22 raspberrypi bos[263011]:     -
> Oct 17 10:50:22 raspberrypi bos[263011]:       err:
> Oct 17 10:50:22 raspberrypi bos[263011]:         message: 2 UNKNOWN: htlc event subscription terminated
> Oct 17 10:50:22 raspberrypi bos[263011]:         stack:
> Oct 17 10:50:22 raspberrypi bos[263011]:           - Error: 2 UNKNOWN: htlc event subscription terminated
> Oct 17 10:50:22 raspberrypi bos[263011]:           -     at Object.callErrorFromStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
> Oct 17 10:50:22 raspberrypi bos[263011]:           -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client.js:331:49)
> Oct 17 10:50:22 raspberrypi bos[263011]:           -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
> Oct 17 10:50:22 raspberrypi bos[263011]:           -     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
> Oct 17 10:50:22 raspberrypi bos[263011]:           -     at processTicksAndRejections (node:internal/process/task_queues:78:11)
>

**Comment by alexbosworth** [comment]
lnd terminated the connection, maybe it's lnd restarting

**Comment by ChuckNorrison** [comment]
You are right, its lnd which is restarting all the time. Thanks
