### ISSUE TITLE
Confusing error message on invalid public key

### ISSUE THREAD

**Issue by lightning-cortado** [alexbosworth/balanceofsatoshis#419]
While setting up `bos open-balanced-channel`, I wasn't sure whether to add the public key or the whole address (e.g as copied from amboss.space)
```
umbrel@umbrel:~ $ bos open-balanced-channel
? Public key of the node to request a balanced open with?
**<public_key>**

err: 
  - 503
  - FailedToConnectToPeer


umbrel@umbrel:~ $ bos open-balanced-channel
? Public key of the node to request a balanced open with?
**<public_key>@<ip>:<port>**

err: 
  - 400
  - ExpectedPartnerPublicKeyToInitBalancedChannel
```
Given the 503, I thought I'd try with the full ip. The error message was very confusing then. I notice in the code that if we don't pass the regex for a valid public key we throw ExpectedPartnerPublicKeyToInitBalancedChannel - https://github.com/alexbosworth/balanceofsatoshis/blob/ee191d188031f63a4bdf45d77d0d59e09909e391/services/initiate_balanced_channel.js#L108-L109

Shouldn't bos throw a more informative error informing the user that the public key is not a valid one?

**Comment by lightning-cortado** [comment]
As for my problem, I should have just connected to the peer (eg via ThunderHub) prior

**Comment by alexbosworth** [comment]
Yes it doesn't have a way to connect to the peer

**Comment by alexbosworth** [comment]
Isn't that what the message says? It expected a public key for an input
