### ISSUE TITLE
Allow for Sats as the primary unit on Telegram Bot output (with pretty number , formatting)

### ISSUE THREAD

**Issue by brianoflondon** [alexbosworth/balanceofsatoshis#442]
Instead of messages like 

⚡️ Sent 0.00017583 to 🤖@lnp2pbot⚡️. Paid routing fee: 0.00000010 - V4VAPP Hive Bridge 0266ad26

could we get sat formats with commas like this and personally I'd love to see new lines for the routing and destination.

⚡️ Sent 17,583 to 🤖@lnp2pbot⚡️. 
Paid routing fee: 10
V4VAPP Hive Bridge 0266ad26

Sometimes I get cross eyed and can't tell if my node just sent 400,000 Sats or 4,000,000 to someone!

If this project was Python I'd easily put the pull request in my self but JS is just too hard for me. BTW the change to include the node on which incoming payments arrive was AWESOMELY useful to me.

BTW if anyone is interested, in the image below, the payments to `03473b92` and `03e3495e` are to Breez and Muun wallets (which one can tell because of the penultimate hops but not from this screen.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/28054569/206896851-28677afd-dc59-4fdf-8dd2-29641680a746.png">

**Comment by alexbosworth** [comment]
did you try the --use-small-units option

**Comment by brianoflondon** [comment]
Well that's a bit embarrassing! Thank you! I've turned that on, much better.
