### ISSUE TITLE
[Feature Idea] Open could allow for opening channels that should be private channels

### ISSUE THREAD

**Issue by alexbosworth** [alexbosworth/balanceofsatoshis#45]
When you do `bos open` there is no way to specify that a channel should be private

This could either be a global `--private` flag or a repeated `--private` flag to correspond with the per public key amounts

**Comment by jansocz** [comment]
This feature is needed (--private flag per public key). I was surprised to find it not beeing supported.

**Comment by alexbosworth** [comment]
It is supported, with the `--type` flag
