### ISSUE TITLE
[invoice] - Zero amount invoices don't add hop hints

### ISSUE THREAD

**Issue by niteshbalusu11** [alexbosworth/balanceofsatoshis#451]
If you run the invoice command with zero amount and include hop hints, it doesn't seem to be adding any. Issue might be in ln-service?

**Comment by alexbosworth** [comment]
what is the command arguments?

**Comment by niteshbalusu11** [comment]
bos invoice —include-hints
Without specifying any amount.

**Comment by alexbosworth** [comment]
that's an lnd level issue

**Comment by niteshbalusu11** [comment]
Ok I’ll open an issue on lnd.

**Comment by alexbosworth** [comment]
I guess it could be worked around on the bos side but we'd need a heuristic for selecting the private channels

**Comment by alexbosworth** [comment]
We could also detect this scenario and error: user creates hop hints flag invoice but invoice doesn't contain hop hints, error

**Comment by niteshbalusu11** [comment]
Yeah we could do that.

**Comment by alexbosworth** [comment]
seems like this got fixed in lnd now

**Comment by niteshbalusu11** [comment]
Cool ok. Thanks.
