### ISSUE TITLE
installation problems BOS on Umbrel

### ISSUE THREAD

**Issue by maxmerlin78** [alexbosworth/balanceofsatoshis#470]
Umbrel Verion 0.5.3

I have carried out the installation routine
and get after npm i -g balanceofsatoshi this error:

umbrel@umbrel:~ $ npm i -g balanceofsatoshis
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellane                                                                                                                                       ous Warning EHOSTUNREACH: request to https://registry.npmjs.org/balanceofsatoshi                                                                                                                                       s failed, reason: connect EHOSTUNREACH 104.16.24.35:443
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a req                                                                                                                                       uest error during revalidation.
npm ERR! code EHOSTUNREACH
npm ERR! errno EHOSTUNREACH
npm ERR! request to https://registry.npmjs.org/ln-sync/-/ln-sync-4.2.0.tgz failed, reason: connect EHOSTUNREACH 104.16.24.35:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/umbrel/.npm/_logs/2023-02-04T09_54_12_030Z-debug.log

here the debug log: 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', '-g', 'balanceofsatoshis' ]
2 info using npm@6.14.17
3 info using node@v14.21.2
4 verbose npm-session 8f19f1a8c5a27c5d
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 warn registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EHOSTUNREACH: request to https://registry.npmjs.org/balanceofsatoshis failed, reason: connect EHOSTUNREACH 104.16.24.35:443
8 warn registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
9 http fetch GET 200 https://registry.npmjs.org/balanceofsatoshis 503ms (from cache)
10 silly pacote tag manifest for balanceofsatoshis@latest fetched in 606ms
11 timing stage:loadCurrentTree Completed in 842ms
12 silly install loadIdealTree
13 silly install cloneCurrentTreeToIdealTree
14 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
15 silly install loadShrinkwrap
16 timing stage:loadIdealTree:loadShrinkwrap Completed in 6ms
17 silly install loadAllDepsIntoIdealTree
18 silly resolveWithNewModule balanceofsatoshis@13.25.0 checking installable status
19 http fetch GET 200 https://registry.npmjs.org/@alexbosworth%2ffiat 276ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/@alexbosworth%2fcaporal 286ms (from cache)
21 http fetch GET 200 https://registry.npmjs.org/abort-controller 273ms (from cache)
22 http fetch GET 200 https://registry.npmjs.org/@alexbosworth%2fhtml2unicode 289ms (from cache)
23 http fetch GET 200 https://registry.npmjs.org/@alexbosworth%2fnode-fetch 282ms (from cache)
24 http fetch GET 200 https://registry.npmjs.org/asciichart 265ms (from cache)
25 http fetch GET 200 https://registry.npmjs.org/bech32 256ms (from cache)
26 http fetch GET 200 https://registry.npmjs.org/async 277ms (from cache)
27 http fetch GET 200 https://registry.npmjs.org/asyncjs-util 280ms (from cache)
28 http fetch GET 200 https://registry.npmjs.org/bip66 269ms (from cache)
29 silly pacote version manifest for @alexbosworth/fiat@1.0.4 fetched in 342ms
30 silly resolveWithNewModule @alexbosworth/fiat@1.0.4 checking installable status
31 silly pacote version manifest for @alexbosworth/caporal@1.4.4 fetched in 355ms
32 silly resolveWithNewModule @alexbosworth/caporal@1.4.4 checking installable status
33 silly pacote version manifest for abort-controller@3.0.0 fetched in 346ms
34 silly resolveWithNewModule abort-controller@3.0.0 checking installable status
35 silly pacote version manifest for @alexbosworth/html2unicode@1.1.5 fetched in 370ms
36 silly resolveWithNewModule @alexbosworth/html2unicode@1.1.5 checking installable status
37 silly pacote version manifest for @alexbosworth/node-fetch@2.6.2 fetched in 371ms
38 silly resolveWithNewModule @alexbosworth/node-fetch@2.6.2 checking installable status
39 silly pacote version manifest for asciichart@1.5.25 fetched in 350ms
40 silly resolveWithNewModule asciichart@1.5.25 checking installable status
41 silly pacote version manifest for bech32@2.0.0 fetched in 342ms
42 silly resolveWithNewModule bech32@2.0.0 checking installable status
43 silly pacote version manifest for async@3.2.4 fetched in 354ms
44 silly resolveWithNewModule async@3.2.4 checking installable status
45 silly pacote version manifest for asyncjs-util@1.2.11 fetched in 353ms

**Comment by alexbosworth** [comment]
you could clone the repo instead

**Comment by maxmerlin78** [comment]
error found, the reason was an old version of npm-global on my node. after update and a restart the installation worked.
