### ISSUE TITLE
[limit-forwarding] Add a flag/option to selectively block a channel for incoming htlcs before closing

### ISSUE THREAD

**Issue by M1ch43lV** [alexbosworth/balanceofsatoshis#473]
Problem: 
Sometimes a channel cannot be closed because the channel is full of stucked htlcs, which cannot be forwarded and it takes a long time to clear. As you are waiting that the old ones are cleared, the possibility is very high that new htlcs are incoming and getting stucked. So a feature is needed that selectively blocks a channel for incoming and outgoing htlcs.

Previous solution: 
1. The command "bos limit-forwarding --disable-forwards" blocks the whole htlc traffic for the node. 
2. In the meantime a new flag was added to selectively block channel pairs with "bos limit-forwarding --deny "incoming pubkey1/outgoing pubkey to block" --deny "incoming pubkey2/outgoing pubkey to block"?
However in case of a large node with more than 50 channels a large list of pubkeys is needed to selectively block the forwarding of a channel.

Favorable solution:
1. Either a function should be implemented to block all incoming htlcs, so that the channel to be closed is not blocked by new ones. As input only channel ID is needed.
2. Or implementation of a flag like "bos limit-forwarding --deny **all**/ outgoing pubkey to block all incoming htlcs for the outgoing pubkey."

**Comment by alexbosworth** [comment]
Potential syntaxes:

- --deny /pubkey --deny pubkey/
- --deny all/pubkey
- --deny */pubkey
- --deny pubkey

For the use case just --deny pubkey might be the most directly addressing the outlined scenario since you want to block both incoming and outgoing htlcs

**Comment by M1ch43lV** [comment]
Great!!! Thank you for the rapid answer and code implementation!

**Comment by alexbosworth** [comment]
I didn't implement it yet, just thinking about what would be a good syntax

**Comment by M1ch43lV** [comment]
Okay. All the possibilities of syntax you wrote down would be a perfect variable solution. I personally would use --deny all/pubkey or --deny */pubkey or --deny pubkey

**Comment by alexbosworth** [comment]
added `--stop <id>` which should serve this purpose
