### ISSUE TITLE
Segmentation fault on 5.40.1 on using Telegram messages

### ISSUE THREAD

**Issue by AbelLykens** [alexbosworth/balanceofsatoshis#49]
Hey @alexbosworth , I am getting segmentation faults. I just did a npm upgrade. I do not get telegram messages, apart from "connected to XXX" messages

```
# bos telegram --node=DeBitcoinFan --connect 9******

is_connected: true
2020-07-06T09:36:45.213Z 🐔 swaply inbound enabled by XXX on 633615x1873x0
Segmentation fault (core dumped)

# bos --version
5.40.1

```

**Comment by alexbosworth** [comment]
> Hey @alexbosworth , I am getting segmentation faults. I just did a npm upgrade. I do not get telegram messages, apart from "connected to XXX" messages
> 
> ```
> # bos telegram --node=DeBitcoinFan --connect 9******
> 
> is_connected: true
> 2020-07-06T09:36:45.213Z 🐔 swaply inbound enabled by XXX on 633615x1873x0
> Segmentation fault (core dumped)
> 
> # bos --version
> 5.40.1
> ```

What if you do npm install -g balanceofsatoshis@5.40.0

Does that version also produce the seg fault?

**Comment by alexbosworth** [comment]
Can you tell me what nodejs version you have as well?

**Comment by AbelLykens** [comment]
Just did  `npm install -g balanceofsatoshis@5.40.0`, running now. 

```
# node -v
v12.15.0
```

**Comment by AbelLykens** [comment]
3 segfaults last night. Will send you my logs in a DM on Slack if that is OK ;)

**Comment by alexbosworth** [comment]
> 3 segfaults last night. Will send you my logs in a DM on Slack if that is OK ;)

You could go to 5.39.5 - I can't repro this but next release may fix it

**Comment by AbelLykens** [comment]
Thanks for your comment @ slack about a possible fix.
For now I will try 5.39.5 ;)

**Comment by AbelLykens** [comment]
No segfaults on 5.39.5, fyi

**Comment by alexbosworth** [comment]
> No segfaults on 5.39.5, fyi

Potentially `telegram` should allow disabling the db component itself

Can you tell me the size of your `data.mdb` file in ~/.bos directory?

**Comment by AbelLykens** [comment]
41M data.mdb

just upgraded, let's see ;)

**Comment by alexbosworth** [comment]
> 41M data.mdb
> 
> just upgraded, let's see ;)

Can you tell me if you are on Windows/Linux/MacOS?

**Comment by AbelLykens** [comment]
> Can you tell me if you are on Windows/Linux/MacOS?

Linux 5.6.19-300.fc32.x86_64 #1 SMP Wed Jun 17 16:10:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
glibc-2.31-2.fc32.x86_64

**Comment by alexbosworth** [comment]
Are you running `telegram` with `--disable-sync` on?

**Comment by AbelLykens** [comment]
Yes, and I do not have the problem any more. Have not tried without.

**Comment by AbelLykens** [comment]
Just tried running without disable sync and got another Segfault, I am on 5.43.1.

**Comment by alexbosworth** [comment]
OK I think this database library doesn't work well across different platforms, I will have to switch it out for a different one

**Comment by alexbosworth** [comment]
The database was removed, I will revisit it at a later date
