### ISSUE TITLE
Updated link

### ISSUE THREAD

**Issue by jtymoszczuk** [alexbosworth/balanceofsatoshis#506]
Under your [Community how to](https://github.com/alexbosworth/balanceofsatoshis#community-howtos)
the link "commands howto" failed on the line below:

"Another rebalance + tags & telegram commands howto"

**I think the new link for it is this**
https://raspibolt.org/guide/bonus/lightning/balance-of-satoshis.html#optional-connect-your-node-to-a-telegram-bot

**Comment by alexbosworth** [comment]
you could edit it here https://github.com/alexbosworth/balanceofsatoshis/edit/master/README.md
