### ISSUE TITLE
[inbound-channel-rules] add variable for existing peers

### ISSUE THREAD

**Issue by feelancer21** [alexbosworth/balanceofsatoshis#510]
I'd like to reject private channels in general, but I don't like to reject if there already exists a channel with the peer. One idea is to add a new variable IS_PEER which is true, if there is already a channel with the peer.

**Comment by alexbosworth** [comment]
Seems similar to #493 to determine if there is existing liquidity with the peer

**Comment by alexbosworth** [comment]
you can use joint_public_capacity formula variable in 15.4.0
