### ISSUE TITLE
telegram bot reconnects often

### ISSUE THREAD

**Issue by martinatime** [alexbosworth/balanceofsatoshis#513]
BOS v14.0.0
LND v0.16.0-beta

Basically since I upgraded LND to 0.16 the telegram bot within BOS seems to connect/re-connect frequently. There doesn't seem to be a pattern to it as far as frequency. The commands seem to work as far as I have used and there is functional but getting the "connected" message gives me more alerts so I'm probably going to have to mute the bot or disable the daemon altogether. Any advice/configuration/etc would be much appreciated.

**Comment by alexbosworth** [comment]
what nodejs version?

**Comment by martinatime** [comment]
checking....

**Comment by martinatime** [comment]
14.21.3

**Comment by alexbosworth** [comment]
i would update to nodejs 16 and stop and restart the bot, 14 is end of life by nodejs https://endoflife.date/nodejs

**Comment by martinatime** [comment]
Thanks, I'm giving that a try. I'll update this if I don't continue to see an issue over the next few hours.

**Comment by alexbosworth** [comment]
also keep an eye on the logs where you are running the bos telegram command

**Comment by alexbosworth** [comment]
make sure to also reinstall bos after you update nodejs

**Comment by martinatime** [comment]
I just saw your comment. I will reinstall bos as I'm still seeing the same issue. I'll keep this issue updated and when I get time I'll go through the logs and try to connect the dots.

**Comment by martinatime** [comment]
ok, I ran 'sudo npm i -g balanceofsatoshis" after your suggestion but I'm still getting the reconnections.


bos -V = 15.0.0
node --version = v20.0.0
npm --version = 9.6.4
lnd --version = lnd version 0.16.0-beta commit=v0.16.0-beta

I have attached the log that shows various errors and then approximately 3-4 minutes following the errors I would get a "Connected" message in telegram.
[bos.log](https://github.com/alexbosworth/balanceofsatoshis/files/11301361/bos.log)

On a side note, I use the Amboss Healthcheck status and my node registered it was down from for about 3 minutes so I'm going to be monitoring my node to see if it has issues.

**Comment by alexbosworth** [comment]
Weird maybe the node is going down and being restarted, i would look at lnd logs

**Comment by martinatime** [comment]
Yep, that is the issue. Apparently, there is some issue with the watchtower client or my configuration to it and it's causing LND to restart. I will attempt to troubleshoot that and create an issue over in LND. I'll go ahead and close this. Thanks for being awesome!
