### ISSUE TITLE
error - SavedNodeMissingMacaroonData

### ISSUE THREAD

**Issue by tagcoin** [alexbosworth/balanceofsatoshis#515]
running under btcpayserver

docker run -it --rm --network="generated_default" -v $HOME/.bos:/home/node/.bos -v $HOME/.lnd:/home/node/.lnd:ro alexbosworth/balanceofsatoshis balance --node xxxxx

credentials.json inside xxxxx folder
{
"socket": "lnd_bitcoin:10009"
}

getting this error

err: 
  - 400
  - SavedNodeMissingMacaroonData

removed all macaroons from lnd data directory, restarted lnd, but same error

any ideas how to solve this?

**Comment by alexbosworth** [comment]
if you use credentials.json you need to put the macaroon or macaroon path and cert or cert path

**Comment by alexbosworth** [comment]
I'm not sure how btcpayserver is laid out, but it will look for the cert at the default path like ~/.lnd/tls.cert

**Comment by tagcoin** [comment]
got it working to a certain state, and after "No connection established" message, added an IP instead of lnd_bitcoin in credentials.json, but now have the TLS error and it pretty much freezes the terminal...tried to replace IP with hostname but then still get "No connection established" - Also trying to run the tradesecret to get into the private telegram group but i think i got the syntax wrong..;)...(docker run -it --rm -v $HOME/.bos:/home/node/.bos alexbosworth/balanceofsatoshis trade-secret: 626f73ff0001010425002302210288be11d147e1525f7f234f304b0)

**Comment by alexbosworth** [comment]
trade-secret will require bos can connect to lnd first

no connection implies some kind of networking issue

**Comment by warioishere** [comment]
> got it working to a certain state, and after "No connection established" message, added an IP instead of lnd_bitcoin in credentials.json, but now have the TLS error and it pretty much freezes the terminal...tried to replace IP with hostname but then still get "No connection established" - Also trying to run the tradesecret to get into the private telegram group but i think i got the syntax wrong..;)...(docker run -it --rm -v $HOME/.bos:/home/node/.bos alexbosworth/balanceofsatoshis trade-secret: 626f73ff0001010425002302210288be11d147e1525f7f234f304b0)

did you get his to work?

if I use the docker containers name of lnd `btcpayserver_lnd_bitcoin`

i get a 

```
- 503
- UnexpectedErrorWhenGettingChainBalance
- 
  err: 
    message: 14 UNAVAILABLE: No connection established. Last error: Hostname/IP does not match certificate's altnames: Host: btcpayserver_lnd_bitcoin. is not in the cert's altnames: DNS:1991ddf8dcfd, DNS:localhost, DNS:lnd_bitcoin, DNS:unix, DNS:unixpacket, DNS:bufconn, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, IP Address:172.18.0.10 (2023-12-30T10:22:35.983Z)
    stack: 
      - Error: 14 UNAVAILABLE: No connection established. Last error: Hostname/IP does not match certificate's altnames: Host: btcpayserver_lnd_bitcoin. is not in the cert's altnames: DNS:1991ddf8dcfd, DNS:localhost, DNS:lnd_bitcoin, DNS:unix, DNS:unixpacket, DNS:bufconn, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, IP Address:172.18.0.10 (2023-12-30T10:22:35.983Z)

```

@alexbosworth do you have an Idea why we dont get bos connected to btcpay servers lnd container?

**Comment by alexbosworth** [comment]
Looks like a networking/tls error so like maybe telnet to the ip if that works then look at the certificate to make sure it's scoped to the ip/name

**Comment by warioishere** [comment]
@alexbosworth 

Hinalex. We got a working config
Thanks to @petzsch

Maybe you can put this into your MD


```
# run as root (run: sudo su -)
nano $HOME/.bos/btcpay/credentials.json

{
  "cert_path": "/root/.lnd/tls.cert",
  "macaroon_path": "/root/.lnd/admin.macaroon",
  "socket": "lnd_bitcoin:10009"
}

docker run --user root:root -it --rm --network=generated_default -v $HOME/.bos:/root/.bos -v /var/lib/docker/volumes/generated_lnd_bitcoin_datadir/_data:/root/.lnd:ro alexbosworth/balanceofsatoshis --node btcpay report
```

Greetings
