### ISSUE TITLE
having error when trying to open a balance channel.

### ISSUE THREAD

**Issue by GFreedomX** [alexbosworth/balanceofsatoshis#526]
hi guys
i got below error

err: 
- "400 
-" Expected Inbound Liquidity On Existing Channel

This error was prompt after I paste a pub key of a node and hit Enter

**Comment by alexbosworth** [comment]
you need inbound liquidity on an existing channel to use the command

**Comment by GFreedomX** [comment]
So I can't use it if I have inbound liquidity but not to the same node? correct me if I am wrong

**Comment by alexbosworth** [comment]
the initiator yes, the accepting side, no

**Comment by GFreedomX** [comment]
i see,
understood on the earlier part
but what do you mean by 
"except to receive the keysend to kick things off"

**Comment by GFreedomX** [comment]
so just to be clear that I understand this correctly
if someone wants to open a balance channel with me
1)the requestor will need to first open a channel to my node
2)then only, the requestor is able to open a 2nd channel ( a balance channel)
