### ISSUE TITLE
[Feature request] option to communicate over Tor or VPN

### ISSUE THREAD

**Issue by openoms** [alexbosworth/balanceofsatoshis#54]
When BoS is communicating with external services like Telegram or the Loop server being able to specify a proxy to go through would be very valuable for privacy by avoiding exposing the public IP address of the node (or the server where BoS is running).

**Comment by alexbosworth** [comment]
I think there is a way to have this work in a container where all traffic goes through a proxy but I don't know exactly the details

Agreed if you don't want to reveal IPs, there is no support for that at the moment

**Comment by alexbosworth** [comment]
Partially addressed in https://github.com/alexbosworth/balanceofsatoshis/pull/174 - remade more specific issue with https://github.com/alexbosworth/balanceofsatoshis/issues/176 - for more other specific changes create new specific issues
