### ISSUE TITLE
[telegram] Error when starting service

### ISSUE THREAD

**Issue by paulofelipe84** [alexbosworth/balanceofsatoshis#541]
I've had the bos-telegram service running on my umbrel for a good while, and suddenly it stopped working. When checking the service status I get:

`umbrel@umbrel:/ $ sudo systemctl status bos-telegram.service
● bos-telegram.service - bos-telegram
   Loaded: loaded (/etc/systemd/system/bos-telegram.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2023-06-22 12:03:10 UTC; 1min 49s ago
 Main PID: 23102 (node)
    Tasks: 11 (limit: 4915)
   CGroup: /system.slice/bos-telegram.service
           └─23102 node /home/umbrel/.npm-global/bin/bos telegram --connect 322648646

Jun 22 12:03:10 umbrel systemd[1]: Started bos-telegram.
Jun 22 12:03:27 umbrel bos[23102]: err:
Jun 22 12:03:27 umbrel bos[23102]:   - 503
Jun 22 12:03:27 umbrel bos[23102]:   - ErrorInPaymentsSub
Jun 22 12:03:27 umbrel bos[23102]:   -
Jun 22 12:03:27 umbrel bos[23102]:     err:
Jun 22 12:03:27 umbrel bos[23102]:       - 503
Jun 22 12:03:27 umbrel bos[23102]:       - ExpectedForwardEventOrLinkFailEventInHtlcEvent`

I haven't found any info about those error messages anywhere. Not sure if I'm not searching it properly.

**Comment by alexbosworth** [comment]
what version

**Comment by paulofelipe84** [comment]
13.0.2

**Comment by paulofelipe84** [comment]
That might mean I need to update it 😅 . Doing that now.

**Comment by paulofelipe84** [comment]
It's updated. The error is gone. Thanks!
