### ISSUE TITLE
"400 - ExpectedFileSystemMethodsToGetTags"

### ISSUE THREAD

**Issue by tuganode** [alexbosworth/balanceofsatoshis#567]
Hi. I'm running the latest version of BoS on a raspibolt node, debian x86_64 with kernel 6+ ,  systemd.    When I run "bos lnurl pay" with the "--avoid" option it raises an error message "400 - ExpectedFileSystemMethodsToGetTags"

**Comment by alexbosworth** [comment]
Should be fixed in the latest update, can you try again?

**Comment by tuganode** [comment]
Okay! 100% !  thank you very much and a merry Christmas.
