### ISSUE TITLE
Huge lack in performance while bos telegram

### ISSUE THREAD

**Issue by ChuckNorrison** [alexbosworth/balanceofsatoshis#57]
I tested the bos telegram in my RaspiBlitz node (Pi 4 B) and it worked great so far. Than i observed kind of performance lags after that installation. cpu was always at 60% on that node process. 

Do you expect that huge performance requirements on this? Iam hosting some telegram bots with python and those guys are running on 3% max.

Can you try to confirm that?

**Comment by alexbosworth** [comment]
Try `--disable-sync`

**Comment by ChuckNorrison** [comment]
I uninstalled and reinstalled, than i entered wrong api key. i updated the file with the api key and after starting bos telegram it fails

> bos@raspberrypi:~/.bos $ bos telegram
> 
> connecting_to_telegram: 
>   (empty array)
> ? Connection code? (Bot command: /connect) Launch failed
> Error: 404: Not Found
>     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/telegraf/core/network/client.js:281:17
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)

I will make a python bot instance iam already using for some private bots:
https://github.com/ChuckNorrison/python-telegram-bot

**Comment by alexbosworth** [comment]
Try removing the api key

**Comment by ChuckNorrison** [comment]
That worked, thanks.

I tested with --disable-sync, so the performance is much better... seems he will not notify anything in this mode

**Comment by alexbosworth** [comment]
Disable sync will not change any of the bot actions or notifications

**Comment by ChuckNorrison** [comment]
ah ok payment notifications, /mempool and /connect tested succesful. /blocknotify stopped to work.

This is great for me so far, thanks

**Comment by alexbosworth** [comment]
blocknotify should still work, the only thing disable sync will change is the log output of the telegram command on the CLI, nothing in the telegram itself should change

**Comment by ChuckNorrison** [comment]
on /help, /blocknotify is not listed, i dont use it and iam fine with this solution, thanks :+1:
