### ISSUE TITLE
bos balance fluctuates with HTLCs

### ISSUE THREAD

**Issue by zapomatic** [alexbosworth/balanceofsatoshis#572]
This may be an issue for LND not serving enough info in the APIs, but it seems that bos balance is fluctuating as the HTLCs are adjusting. As a node with dozens of in-flight HTLCs constantly, using `bos balance` does not provide a reliable snapshot of the funds that belong to the node. Running `bos balance` repeatedly returns amounts that are +- hundreds or millions of sats.

Is this because one side of the HTLC may be accounted for but not the other? Or is it a timing issue with gathering the stats while an HTLC comes or goes?

To illustrate, running this on my node just now:

```
for i in {1..10}; do bos balance; done
```

produces 10 outputs that contain the following numeric diffs from the prior output:

```
0
131,262
29,475
-183,471
418,886
-45,778
200,202
-19,258
-42,071
-312,242
```

**Comment by zapomatic** [comment]
To clarify user expectations, I would think that `bos balance` would return an answer to the question of "What number of sats does this node own if all current HTLCs are assumed to fail/cancel?"

**Comment by alexbosworth** [comment]
did you try using bos balance --detailed

**Comment by zapomatic** [comment]
That seems to be more what I'm looking for (the `offchain_balance` output from --detailed). Thanks!
