### ISSUE TITLE
[BUG] Wrong fee-rate on fund with multiple utxos

### ISSUE THREAD

**Issue by bota87** [alexbosworth/balanceofsatoshis#587]
I've build a transaction with 2 taproot input and 1 segwit output with this command but the resulted fee rate it's lower than asked

`bos fund <address> max --fee-rate 1.9 --select-utxos`

**Comment by alexbosworth** [comment]
fractional arguments aren't interpreted because LND accepts int values on a per vbyte level for fund psbt

**Comment by bota87** [comment]
Can I suggest to add a warning or an error in this case?

**Comment by alexbosworth** [comment]
It has been added in the latest version
