### ISSUE TITLE
UnexpectedResponseInHistoricRateResponse Error

### ISSUE THREAD

**Issue by tdickman** [alexbosworth/balanceofsatoshis#59]
When attempting to run the following command (or any `bos accounting` command):

```
bos accounting chain-fees --month 8 --year 2020 --csv
```

The command hangs for several minutes, then returns:

```
UnexpectedResponseInHistoricRateResponse
```

**Comment by alexbosworth** [comment]
try `--rate-provider coincap`

**Comment by tdickman** [comment]
Bingo, that fixed it. Thanks for the quick response!
