### ISSUE TITLE
UnexpectedPendingChannelsErr error running 2 accounting commands

### ISSUE THREAD

**Issue by tdickman** [alexbosworth/balanceofsatoshis#6]
When I run the following 2 commands:

```
bos accounting chain-sends
bos accounting invoices
```

I receive the error:

```
err:
  - 503
  - UnexpectedPendingChannelsErr
  -
    err:
      message: 14 UNAVAILABLE: failed to connect to all addresses
      stack:
        - Error: 14 UNAVAILABLE: failed to connect to all addresses
        -     at Object.exports.createStatusError (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grpc/src/common.js:91:15)
        -     at Object.onReceiveStatus (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:1209:28)
        -     at InterceptingListener._callNext (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:568:42)
        -     at InterceptingListener.onReceiveStatus (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:618:8)
        -     at callback (/home/tom/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/grpc/src/client_interceptors.js:847:24)
```

This could be related to [this issue](https://github.com/lightningnetwork/lnd/issues/3716).

**Comment by alexbosworth** [comment]
So LND is returning this error when it tries to get information about pending channels

If you do `lncli pendingchannels` do you see an error?

**Comment by tdickman** [comment]
I do not see any error. It returns a json of channel closures with 3 pending force closures.

**Comment by alexbosworth** [comment]
When you try the accounting commands that fail, do you see anything like [ERR] or [WRN] in the LND logs around that time?

**Comment by tdickman** [comment]
I do not see any errors in the LND logs when it fails. Interestingly, the commands succeed if I retry them a few times (~50% of the time), so I can still get the data.

**Comment by tdickman** [comment]
Just ran it ~20x with no failures.

**Comment by alexbosworth** [comment]
Interesting, maybe in combination with another call then it can sometimes fail but that is odd

**Comment by alexbosworth** [comment]
Did this go away conclusively?

**Comment by tdickman** [comment]
It has not cropped up since then (just tested a few more times). Closing for now - if I run into this again, I'll reopen.

As always, thank you for all the help debugging!
