### ISSUE TITLE
[feature idea] opening balanced channels

### ISSUE THREAD

**Issue by nolith** [alexbosworth/balanceofsatoshis#64]
When you do `bos open` there is no way to specify that a channel should push some sats on the other side.

This should be a repeated `--push_amount` flag to correspond with the peer public key amount

**Comment by alexbosworth** [comment]
How about --give

bos open <pubkey> --amount <amount> --give <give>

**Comment by nolith** [comment]
Sounds good to me. It's more clear than the push amount semantic we have on lnd.

**Comment by alexbosworth** [comment]
Should be available in 5.47.0

**Comment by nolith** [comment]
Tested today. Works like a charm! 🎉

Thank you for the effort!
