### ISSUE TITLE
Problem connecting to remote node

### ISSUE THREAD

**Issue by cryptomortis** [alexbosworth/balanceofsatoshis#7]
followed instructions to make ~/.bos/mynode/credentials.js:

```
{
"macaroon": "mymacaroon==",
"cert": "mycert==",
"socket": "mynode.mysite.io:10009"
}
```

When I run `bos nodes`, error:

```
balanceofsatoshis/nodes/get_saved_nodes.js:103
          if (!credentials.macaroon) {
                           ^
TypeError: Cannot read property 'macaroon' of undefined
```

lnd version 0.8.0-beta commit=v0.8.1-beta
bos 5.6.2
node v10.17.0

**Comment by alexbosworth** [comment]
I think the fix here is to give a better error message if you use a `.js` and not a `.json` for the credentials

**Comment by alexbosworth** [comment]
Actually the new way to do this is just to use the add node functionality and not mess around directly with credential files
