### ISSUE TITLE
[Feature idea] Ignore forwards smaller than configured amount

### ISSUE THREAD

**Issue by AbelLykens** [alexbosworth/balanceofsatoshis#89]
I'd like to be able to do this:

    bos telegram --connect 9187562 --ignore-forwards-smaller-than 100

I do not care about a 1-5 sat payment every minute. The higher ones are interesting :D . Less noise, more signal ;)

**Comment by alexbosworth** [comment]
Try the most recent release

**Comment by AbelLykens** [comment]
You the man
