### ISSUE TITLE
[bug] Price value formatting

### ISSUE THREAD

**Issue by andrerfneves** [alexbosworth/balanceofsatoshis#9]
Not sure if I'm missing something here but seems like the formatting of the BTCUSD price rate is incorrect?

<img width="524" alt="Screen Shot 2020-02-16 at 9 55 15 AM" src="https://user-images.githubusercontent.com/2574011/74606934-88e73800-50a2-11ea-826f-a06a4bbf5bc7.png">

Shouldn't it be `9908.81666999`?

**Comment by alexbosworth** [comment]
It's in cents, if you want a dollar based version you could try `bos market` which will also give you a chart

**Comment by andrerfneves** [comment]
Ah, makes sense. Not sure how I missed that one. Thanks
