### ISSUE TITLE
Paths are not discarded despite exceeding max-fee-rate

### ISSUE THREAD

**Issue by Fittiboy** [alexbosworth/balanceofsatoshis#90]
Currently, if a route which produces no channel failure is found, amounts will be evaluated even if the set `max-fee-rate` is exceeded.
While the maximum total fee spent depends on the amount that is rebalanced, the effective fee rate for a given route is fixed.
Any route which exceeds the set `max-fee-rate` should be discarded immediately, before the `evaluating_amount` step is started.

**Comment by alexbosworth** [comment]
This is by design

**Comment by alexbosworth** [comment]
LND generally will use the lowest possible fee route so if you see a route explored that looks like it would be too high fee, just cancel the rebalance command
