### ISSUE TITLE
Fund batch open channels with lncli wallet funds

### ISSUE THREAD

**Issue by count-null** [alexbosworth/balanceofsatoshis#94]
Currently, batch opening channels with `bos open ...` returns some details for a pay-to-many transaction and awaits a PSBT that pays it.

Could there be an option to allow `bos` to spend directly from the lncli wallet? This would remove the need for the operator to manually construct the PSBT and paste in the hex if they already have sufficient balance in their lightning onchain wallet. 

Any thoughts?

**Comment by alexbosworth** [comment]
You can use `bos fund` for spending from the lnd wallet, but this requires lnd 0.12.0 or later

**Comment by count-null** [comment]
Using `bos fund` I was able to batch open two channels on testnet. Closing this issue. Thanks Alex!

Here's the steps:

`bos open <pubkey> --amount <sats> <pubkey2> --amount <sats>`

When I ran this, it returned:

    Addresses:
    
    tb1q8f573zcaxtrdmh50muwmn5yly4wka4fej67xm5jxljed6wuu4yzq52gr0t, 0.01000000
    
    tb1qpyz6lausga2s7j2wld8a6m6z722zz4gwkk5cc2hhkq0wj49xfahsck9ajc, 0.01000000 

In a new terminal,

`bos fund tb1q8f573zcaxtrdmh50muwmn5yly4wka4fej67xm5jxljed6wuu4yzq52gr0t 1000000 tb1qpyz6lausga2s7j2wld8a6m6z722zz4gwkk5cc2hhkq0wj49xfahsck9ajc 1000000`

This command returns signed hex. I copied it to the other terminal where the `bos open` command was waiting.

I was able to do this in less than a minute.

NOTE: the open command gives you funding amounts in BTC (i.e. 0.01000000) but you need to enter sats in the fund command (i.e. 1000000)

**Comment by alexbosworth** [comment]
Great, potentially they could be tied together more closely in a future upgrade
