### ISSUE TITLE
bos open stalls after connecting to peers

### ISSUE THREAD

**Issue by count-null** [alexbosworth/balanceofsatoshis#95]
Using bos v8.0.2 and lncli version 0.12.1-beta, the `bos open` command to batch open many channels stalls after establishing peer connections to all the nodes listed.

I have confirmed that the command successfully establishes the peer connections. When I run the same command again, it no longer shows `connecting _to:` indicating that the nodes are already peers. 

Heres the example output: 

```
$ bos open 03ef9148e4e0f120c55c05ed91f77bb1adf256694391bf81a07f835a6384348dd4 --amount 1000000 02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b --amount 1000000 038a7f830db2bdc5474a9b61e505814a5b5b6ef3f0c9ce513c4d21d5b9bfbb26e2 --amount 1000000 03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f --amount 1000000

-
  node:              Boltimore
  channels_per_peer: 1.17
-
  node:                        rompert.com🔵
  channels_per_peer:           1.04
  is_accepting_large_channels: true
-
  node:              BitcoinForAll
  channels_per_peer: 1.33
-
  node:                        ACINQ
  channels_per_peer:           1.25
  is_accepting_large_channels: true

opening_to:
  - Boltimore: 0.01000000
  - rompert.com🔵: 0.01000000
  - BitcoinForAll: 0.01000000
  - ACINQ: 0.01000000
```

This is all the command outputs. It does not show anything else even after waiting for 10+ mins. The `bos open` process uses 0% CPU as well.

**Comment by alexbosworth** [comment]
Potentially it is waiting for one of these peers to respond and it isn't, I'd try them one by one and then press enter to cancel to identify if there is a problematic one

**Comment by count-null** [comment]
I let the command run for over 20 mins and it finally returned. I also ran them separately and identified the problem node. Is there any risk paying the funding transaction even though it may have taken more than 10 mins for the `bos open` command to return anything? Is the `funding_deadline` displayed still accurate?

**Comment by alexbosworth** [comment]
The funding deadline is still accurate yes I would just avoid that peer

**Comment by count-null** [comment]
Ok, I ignored the advise and tried to fund the opening transaction with the misbehaving peer anyways. After pasting the hex, the `open` command returned:

```
err:
  - 503
  - UnexpectedErrorValidatingChanFunding
  -
    err:
      message: 2 UNKNOWN: no funding intent found for pendingChannelID(088cc947b43d31677aac670b13d10e1725d3b372ba820a20fa91fd2474287cda)
      stack:
        - Error: 2 UNKNOWN: no funding intent found for pendingChannelID(088cc947b43d31677aac670b13d10e1725d3b372ba820a20fa91fd2474287cda)
        -     at Object.callErrorFromStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
        -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
        -     at Object.onReceiveStatus (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
        -     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
        -     at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

With the pending channel ID being the one with the bad peer. 

So I gave up and ran it again without the bad peer and everything works! Thanks for your help! I saved so much on fees!

**Comment by alexbosworth** [comment]
It runs a safety check before allowing the broadcast to try and save you from problems

I think it could do more and show you more about what's going on but that would require LND changes
