### ISSUE TITLE
docker - default macaroon directory not working

### ISSUE THREAD

**Issue by miketwenty1** [alexbosworth/balanceofsatoshis#96]
Attempting to run this in docker. 

alias bos="docker run -it --rm `-v $HOME/.lnd:/home/node/.lnd` -v $HOME/.bos:/home/node/.bos alexbosworth/balanceofsatoshis"

I believe I would need to add something like this: `-v $HOME/.lnd:/home/node/.lnd` 
where "$HOME/.lnd" would be:
```
.
├── data
│   └── chain
│       └── bitcoin
│           └── mainnet
│               └── admin.macaroon
└── tls.cert
```
This appears to pick up the tls.cert but I get an error below. Would this be a bug in your code not using the default location for admin.macaroon?

```
err: 
  - 503
  - FailedToGetMacaroonFileFromDefaultLocation
```

**Comment by alexbosworth** [comment]
it should pick it up from the default location if it has access, access control problems is usually the issue

**Comment by miketwenty1** [comment]
@alexbosworth 
yes closing. Thanks Bos! I was confused by the error. 

For those looking to give explicit permission to the unix file
You can can  `chgrp 1000 admin.macaroon`
and then `chmod 440 admin.macaroon`

**Comment by RemoRitzmann** [comment]
Hi all, trying to use bos on raspiblitz, but get an error
when running bos@raspberrypi:~ $ **bos open-balanced-channel**
err: 
  - 503
  - FailedToGetMacaroonFileFromDefaultLocation

**Comment by alexbosworth** [comment]
You can use the saved nodes feature to specify the path to the macaroon

**Comment by RemoRitzmann** [comment]
furthermore I cannot find admin.macaroon here:
root@raspberrypi:/mnt/hdd/lnd/data/chain/bitcoin/mainnet# ls
macaroons.db  macaroons.db.last-compacted

**Comment by RemoRitzmann** [comment]
saved nodes feature? can you be more specific, newbie here..

**Comment by alexbosworth** [comment]
There are some notes here: https://github.com/alexbosworth/balanceofsatoshis#saved-nodes

**Comment by alexbosworth** [comment]
> furthermore I cannot find admin.macaroon here: root@raspberrypi:/mnt/hdd/lnd/data/chain/bitcoin/mainnet# ls macaroons.db macaroons.db.last-compacted

you'd need to find where your macaroons are though

**Comment by RemoRitzmann** [comment]
I was not able to find admin.macaroon. I just installed bos, might they not yet be created? I've installed with raspiblitz "Install Balance of Satoshis from the SERVICES menu"

**Comment by RemoRitzmann** [comment]
Same Problem: root@raspberrypi:/home/admin/config.scripts# sudo su bos
bos@raspberrypi:/home/admin/config.scripts $ bos open-balanced-channel
err: 
  - 503
  - FailedToGetMacaroonFileFromDefaultLocation

**Comment by alexbosworth** [comment]
I'm not sure where rpiblitz puts things, maybe ask there? I would think it would just work if you can install it from their install flow

**Comment by RemoRitzmann** [comment]
Can you tell me more about macaroons, are these files from LND or C-Lightning? Because LND is installed parallel but makes problems too.

**Comment by RemoRitzmann** [comment]
made a new LND wallet and now I found it here root@raspberrypi:/mnt/hdd/lnd/data/chain/bitcoin/mainnet/admin.macaroon

**Comment by RemoRitzmann** [comment]
chgrp 1000 admin.macaroon
chmod 440 admin.macaroon
root@raspberrypi:/mnt/hdd/lnd/data/chain/bitcoin/mainnet# ls -lS
-rw------- 1 bitcoin bitcoin 524288 Mar 20 09:04 wallet.db
-rw-r--r-- 1 bitcoin bitcoin  32768 Mar 20 08:33 macaroons.db
-r--r----- 1 bitcoin pi         293 Mar 20 08:33 admin.macaroon
-rw-r--r-- 1 bitcoin bitcoin    217 Mar 20 08:33 readonly.macaroon
-rw-r--r-- 1 bitcoin bitcoin    132 Mar 20 08:33 invoice.macaroon
-rw-r--r-- 1 bitcoin bitcoin    114 Mar 20 08:33 walletkit.macaroon
-rw-r--r-- 1 bitcoin bitcoin     92 Mar 20 08:33 signer.macaroon
-rw-r--r-- 1 bitcoin bitcoin     91 Mar 20 08:33 invoices.macaroon
-rw-r--r-- 1 bitcoin bitcoin     91 Mar 20 08:33 router.macaroon
-rw-r--r-- 1 bitcoin bitcoin     83 Mar 20 08:33 chainnotifier.macaroon
-rw-r--r-- 1 bitcoin bitcoin     45 Mar 20 08:35 channel.backup
-rw------- 1 bitcoin bitcoin      8 Mar  6 00:16 macaroons.db.last-compacted

**Comment by RemoRitzmann** [comment]
Ok, my goal was to get bos working on my raspiblitz. But bos only works with LND (am I right?) Since I have C-Lightning working, there is only my C-Lightning wallet working and filled with sats. In the meantime, I have LND wallet set up, but LND is not working because of missing macaroons. 
  http://"IP":3000/rtl/error
  Lnd get info failed due to bad or missing macaroon! please check rtl-config.json to verify the setup!
I don't want to have two wallets. I think I'm messed up with LND and C-Lightning so I sadly cannot use bos yet.

**Comment by alexbosworth** [comment]
OK, maybe check with rpiblitz on how to run things, I'm not sure how that works
