### ISSUE TITLE
Rebalancing not possible

### ISSUE THREAD

**Issue by janis-mueller** [alexbosworth/balanceofsatoshis#97]
When try to execute the command `bos rebalance -v` on my raspiblitz v.1.6.3 I always get:
 `err: 
  - 400
  - NoInboundChannelIsAvailableToReceiveRebalance`
I am using lnd version 0.12.1-beta commit=v0.12.1-beta together with bos 8.0.3
Rebalancing used with  bos used to work fine before.
Not sure which infos may still be useful to get a solution for this issue, but would love to get an idea of what may be causing it.

**Comment by alexbosworth** [comment]
You can set `--in` to specify the inbound peer yourself

This means that there is no automatic choice, meaning inbound liquidity is low

**Comment by janis-mueller** [comment]
> You can set `--in` to specify the inbound peer yourself
> 
> This means that there is no automatic choice, meaning inbound liquidity is low

Thanks, I have a lot of inbound liquidity (many channels with a lot of remote capacity) so I wonder why this is an issue. Going to try the --in option though, thanks!

**Comment by alexbosworth** [comment]
More specifically it's looking for low fee peers with more than around 0.08 BTC inbound

For --in you can specify a peer alias, public key or start of public key, or a tag

**Comment by janis-mueller** [comment]
> More specifically it's looking for low fee peers with more than around 0.08 BTC inbound
> 
> For --in you can specify a peer alias, public key or start of public key, or a tag

Thanks a lot for the fast reply, I am getting along with that option now, awesome

**Comment by janis-mueller** [comment]
one last thing - rebalancing seems to work again but fails because it says fees are too high, but fees look fine, how can I tell bos a max fee limit so that rebalancing goes through? didn't see this in any of the available options

**Comment by alexbosworth** [comment]
You can set `--max-fee-rate` and `--max-fee`

**Comment by janis-mueller** [comment]
> You can set `--max-fee-rate` and `--max-fee`

awesome, must have overlooked it, you are the man!
