### ISSUE TITLE
rebalance inexplicably fails

### ISSUE THREAD

**Issue by jchia** [alexbosworth/balanceofsatoshis#98]
I'm having trouble using rebalance. Both peers are large and expected to be well-funded and well-connected. I don't think it's a problem with balances on my channels because I should be getting errors like NoOutboundPeerWithSufficientBalance in that case and my remote balance on fahrenheit451 and local balance on Umbrel are both much larger than the rebalance amount. What could be causing the failure?

```
$ lnd --version
lnd version 0.11.1-beta commit=v0.11.1-beta
$ bos --version
8.0.5
$ bos rebalance --in 0309bd6a02c71f288977b15ec3ac7283cfdd3d17dde65732981d5a718aa5fb0ebc --out 0297a77f4d1ccc55d7a10a9b137119b1103d9a9d38a5a97ffa1d0152c818fcdd0a --amount 50000 -v

outgoing_peer_to_increase_inbound: ☂ Umbrel (getumbrel.com) 0297a77f4d1ccc55d7a10a9b137119b1103d9a9d38a5a97ffa1d0152c818fcdd0a
incoming_peer_to_decrease_inbound: fahrenheit451 0309bd6a02c71f288977b15ec3ac7283cfdd3d17dde65732981d5a718aa5fb0ebc
rebalance_target_amount:           0.00050000

circular_rebalance_for: ..........

err: 
  - 400
  - FailedToFindPathBetweenPeers
```

**Comment by alexbosworth** [comment]
Usually it's LND not returning any routes, is it only this pair?

**Comment by jchia** [comment]
No, not only this pair. At least one other pair with completely different nodes has the same problem. Rebooting my node also did not help. I tried using `lncli sendpayment` to send a self-payment but I got FAILURE_REASON_NO_ROUTE:

```
$ lncli sendpayment --dest ........ --allow_self_payment --amt 200000 --payment_hash ........
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
| HTLC_STATE | ATTEMPT_TIME | RESOLVE_TIME | RECEIVER_AMT | FEE | TIMELOCK | CHAN_OUT | ROUTE |
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
+------------+--------------+--------------+--------------+-----+----------+----------+-------+
Amount + fee:   0 + 0 sat
Payment hash:   ........
Payment status: FAILED, reason: FAILURE_REASON_NO_ROUTE
[lncli] FAILED
```

I'm not sure what's causing this. `lncli listchannels` shows all my channels as having increasing 'uptime'.

At this point, I suppose it's not a bos problem per se but rather a LN problem.

**Comment by alexbosworth** [comment]
You can try `lncli resetmc` and then try the command again, maybe that will make a difference?

**Comment by jchia** [comment]
After `lncli resetmc`, the `lncli sendpayment` still failed in the same way as before.

**Comment by alexbosworth** [comment]
Maybe check on the channels involved in your graph, to see if they are disabled

**Comment by jchia** [comment]
Yes, `lncli describegraph` indicates that all my node's edges are disabled. I'm investigating why.

**Comment by jchia** [comment]
The channels become enabled and I was able to get rebalance to work.
